export interface GuideChapter {
  id: string;
  section: string;
  title: string;
  lede: string;
  factory: string;
  requires: string;
  measure: string;
  good: string;
  fail: string;
  steps: string[];
  /** Extra search needles so “caliper” hits the hoses/calipers check. */
  searchExtra?: string;
}

function ch(c: GuideChapter): GuideChapter {
  return c;
}

export const GUIDE_SECTION_ORDER = [
  "1. Fluids",
  "2. Engine bay",
  "3. Transmission",
  "4. Brakes & rolling",
  "5. Steering / driveline",
  "6. Underbody",
  "7. Cabin & safety",
  "8. Road test",
  "9. Result",
] as const;

export const GUIDE_CHAPTERS: GuideChapter[] = [
  ch({
    id: "fluids.oilLevel",
    section: "1. Fluids",
    title: "Engine oil",
    lede: "2005 Armada 5.6L VK56DE. Oil-change visit: drain, filter, fill — record type, quarts, filter PN, crush washer. Do not read the dipstick after you dumped the pan. 15k / 30k / baseline: hot reading, engine off, more than 10 minutes.",
    factory:
      "Genuine Nissan 5W-30 full synthetic. Capacity with filter 6.2 L / 6½ qt. Change every 3,500–5,000 miles or 6 months at this mileage. New crush washer on the drain plug every time. Confirm torque and filter PN in FSM SM5E-1T60U1.",
    requires:
      "Oil-change visit: type, amount used, filter PN, crush washer replaced Y/N, mileage from the header. Not color. Not level. 15k / 30k: level ground, engine at operating temperature, key OFF, wait MORE THAN 10 MINUTES, read between L and H on the engine stick — not the trans stick.",
    measure:
      "Oil change: drain hot, swap filter, new crush washer, fill 6½ qt 5W-30, run, shut down, glance the pan and filter for leaks. Write type / quarts / filter PN / washer. 15k dipstick: engine oil stick is left/front, long yellow or marked handle. Pull, wipe lint-free, seat fully, pull again. L = low, H = high.",
    good: "Oil change: 5W-30 in, about 6.5 qt, filter PN written, crush washer Y, no drip at the pan. 15k: film between L and H. Dark brown at high miles is normal. No fuel smell, not gritty, not chocolate-milk milky.",
    fail: "Oil change: old washer reused, unknown filter, Dexron poured, no amount written. 15k: below L add 5W-30 a little at a time. Above H: drain a little. Milky chocolate-milk oil: coolant in the oil — do not run it.",
    steps: [
      "Oil-change visit: warm the engine, drain the pan, replace the filter, new crush washer on the plug. Confirm plug torque in FSM SM5E-1T60U1. Do not guess.",
      "Fill Genuine Nissan 5W-30 full synthetic. Capacity with filter is 6.2 L / 6½ qt. Do not dump 8 qt “to be safe.”",
      "Write oil type, amount used, filter PN, crush washer Y/N. Mileage is the number already in the Vehicle header. Check the box. Do not fill Color / level — you just emptied the pan.",
      "Run it, shut it down, look at the pan rail and the filter for a drip. That leak look is the next walk step.",
      "15k / 30k / baseline only: after warmup, engine OFF more than 10 minutes, then the dipstick. Pull, wipe, seat, pull. Log color/level and any quarts added. That is not an oil-change visit.",
    ],
  }),
  ch({
    id: "fluids.oilLeak",
    section: "1. Fluids",
    title: "Engine oil leak check",
    lede: "VK56 common seeps: valve covers, oil-cooler O-ring at the block, oil pan, front cover / timing cover, filter. Heat after a drive makes fresh wetness show.",
    factory:
      "No published “allowed drip rate.” Seepage that wets a finger is a leak. Damp dusty film on an old gasket at high miles is common. Active dripping is not. Photograph wetness.",
    requires:
      "Find the source before you keep adding oil. Fresh puddles on the ground are a find-it-now item. Do not crawl under a cheap scissor jack — stands on the frame, or a lift.",
    measure:
      "Cold: look at the pavement where it sat overnight (honey/black = oil). After a drive, engine off a few minutes: flashlight on valve covers, oil-cooler adapter at the block, filter, pan rail, front cover. Wipe a finger — fresh wet vs dusty film.",
    good: "No fresh wet finger. No drip on the ground. Old dusty stain at 270k can be logged as a watch item.",
    fail: "Active drip, wet oil-cooler O-ring, soaked timing cover, or a puddle. Schedule gasket/O-ring/cooler work. Do not ignore a leak that empties the stick between visits.",
    steps: [
      "Before you start it, look at the ground. Note color: honey/black = oil.",
      "After the drive, park level. Engine off. Wait a few minutes so you do not burn yourself.",
      "Flashlight: both valve covers, oil-cooler adapter at the block (very common seep on this engine), filter housing, pan and drain plug, front / timing cover.",
      "Wipe. Fresh wet oil is a fail. Dusty brown film that does not wet the finger is a note.",
      "Photograph the wet area. Write which corner of the engine is wet.",
    ],
  }),
  ch({
    id: "fluids.coolant",
    section: "1. Fluids",
    title: "Coolant reservoir level & color",
    lede: "Read the plastic overflow tank COLD. Never open the radiator cap on a hot VK56. Oil film or red tint in the coolant is SMOD in the other direction.",
    factory:
      "50/50 Nissan Long Life (or matching HOAT) and distilled water only. System capacity about 14.4 L / 3¾ gal including the reservoir. Service about 60,000 miles / 5 years if history is unknown. Never tap water. Never mix orange Dex-Cool into this system.",
    requires:
      "Engine COLD. Level between MIN and MAX molded in the tank. Color uniform — not rusty, not oily, not sludged. Cap on the reservoir seated. Do not open the radiator cap hot.",
    measure:
      "Stand at the front bumper. Translucent tank beside the radiator, MIN/MAX on the plastic. Shine a light through it. Do not read the radiator itself. Note color and whether the cap is fully seated.",
    good: "Between MIN and MAX (near MAX is fine). Uniform green/blue/whatever was last poured. No oil film, no rust mud, no sweet oily red tint.",
    fail: "Below MIN or empty: do not drive. Milky / oil film / red ATF tint: oil-cooler or SMOD — stop and treat as mixed fluids. Muddy rust: flush cold. If the tank is full but it later runs hot, the cap, radiator, or water pump is next — do not just add water.",
    steps: [
      "Engine cold. Hood open. Do not start it yet.",
      "Read MIN/MAX on the overflow tank. Photograph the level.",
      "Look for oil sheen or strawberry tint. That is coolant mixing with oil or ATF.",
      "Confirm the reservoir cap is seated.",
      "Do not open the radiator cap. If a cold service is due (unknown at 270k), drain cold, flush with distilled water, refill 50/50 Nissan LL, squeeze hoses, run to temp, cool, recheck.",
    ],
  }),
  ch({
    id: "fluids.atf",
    section: "1. Fluids",
    title: "ATF — dipstick HOT",
    lede: "This reading saves the RE5R05A. Wrong method adds fluid you should not, or misses coolant in the ATF. Idle, shift P-R-N-D, HOT marks, stick inserted reversed.",
    factory:
      "Only Genuine Nissan Matic J. Matic S is the later factory-accepted substitute. Do not pour Dexron, Mercon, or “universal ATF.” Dry fill about 11¼ qt / 10.6 L. A pan drain only comes out about 4–6 qt. Factory HOT check is ATF near 149°F (65°C). Drain/fill when hot, factory about 176°F / 80°C. 30k cadence.",
    requires:
      "Level pavement. Engine IDLING. In Park. After a 10–15 min mixed drive (engine gauge in the middle). Stick inserted REVERSED until the handle contacts the tube. Read HOT marks, not COLD. Never check with the engine off, on a slope, or in gear.",
    measure:
      "Passenger-side firewall, long tube, small bolt through a tab on the handle — that bolt must come out. Wipe with lint-free paper, not a fuzzy rag. Reinsert reversed, pull, read HOT hashes. Then look at color and smell on the paper. Bolt the handle back down.",
    good: "Level in the HOT range. Transparent red or amber. Smells like ATF. No glitter.",
    fail: "Pink, milky, strawberry, or sweet: SMOD. Coolant is in the ATF. Park it. Do not “see if it shifts.” Brown/varnish/burnt: old or overheated — drain/fill Matic J/S. Metal glitter: pan drop. Low and still red: find the leak before you keep adding. High: often a cold reading mistaken for hot — recheck HOT, drain excess if truly over full.",
    steps: [
      "Drive 10–15 minutes of mixed use until the temp gauge sits in its normal middle. Come back to level pavement. Parking brake on. Engine stays running at idle.",
      "Foot on the brake. Shift slowly P → R → N → D → 2/1 if those gates exist → back to P. Pause one second in each. Leave it in P.",
      "Remove the small bolt that pins the trans-stick handle. Pull. Wipe lint-free.",
      "Slide the stick back in REVERSED from the way it normally sits, until the cap/handle contacts the top of the tube. Factory procedure. Pull and read the HOT marks.",
      "Look at color and smell on the paper. Bolt the handle down so the stick cannot walk out.",
      "Add Matic J or S only, a little at a time, engine idling, if it is truly low on a HOT reading. Recheck HOT. Never dump 11 quarts — the converter still holds fluid.",
    ],
  }),
  ch({
    id: "fluids.psf",
    section: "1. Fluids",
    title: "Power steering fluid",
    lede: "Nissan PSF only. COLD marks when the truck has sat. HOT marks after the drive. The high-pressure hose is a common leak on this chassis.",
    factory:
      "Nissan PSF (or the exact Nissan-specified equivalent). Read COLD range engine off after a sit. Read HOT range after the road test. Do not overfill above the top mark.",
    requires:
      "Engine off for the cold reading. Reservoir marked PSF. Fluid red or amber, not black, not burnt. Reservoir and high-pressure hose dry.",
    measure:
      "Find the PSF reservoir in the engine bay — COLD and HOT ranges on the cap or body. Engine off, read COLD MAX/MIN. After the drive, recheck HOT. Note color and whether the high-pressure hose (to the rack) is wet.",
    good: "At or near COLD MAX when cold. In the HOT range after a drive, not above the top mark. Red/amber, not burnt. Dry hose and reservoir.",
    fail: "Below MIN. Foamy (air in the system). Black/burnt. Wet high-pressure hose or rack — schedule the hose/rack. Do not keep topping a leak.",
    steps: [
      "Engine off. Read COLD MAX/MIN. Photograph the level.",
      "Note color: red/amber vs black.",
      "Look at the high-pressure hose and the rack boots. Wet PSF is a leak.",
      "After the drive, engine off a minute, read the HOT range. Still not above the top mark.",
      "Top only with Nissan PSF if it is truly low, then find why.",
    ],
  }),
  ch({
    id: "fluids.brake",
    section: "1. Fluids",
    title: "Brake fluid",
    lede: "Firewall, driver’s side. DOT 3 from a sealed bottle. Level follows pad wear — a sudden drop is a leak, not “add and go.”",
    factory:
      "DOT 3. Flush every 24 months regardless of miles. Never DOT 5 silicone. Never an old open bottle. Reservoir never allowed to run dry during a bleed.",
    requires:
      "Level between MIN and MAX on the master-cylinder reservoir. Color light honey / pale yellow. Cap sealed. Below MIN means worn pads or a leak — find which.",
    measure:
      "Wipe the cap area first so dirt does not fall in. Read MIN/MAX on the side of the translucent reservoir. Note color: clear-amber vs dark brown/black.",
    good: "Between MIN and MAX. Light honey / pale yellow. Cap fully seated. Pedal later proves firm.",
    fail: "Below MIN. Dark brown or black: hygroscopic old fluid — flush DOT 3, one corner at a time, two-person or pressure bleeder. Wetness at the master = do not drive it. Wrong fluid or air left in the circuit is a sinking pedal.",
    steps: [
      "Engine off. Wipe the cap. Read MIN/MAX. Photograph.",
      "Note color (clear-amber vs dark) and that the cap is sealed.",
      "If dark or overdue 24 months: DOT 3 from a sealed bottle, one corner at a time, reservoir never dry, until the bleeder runs clean. If you have not bled brakes before, this is a shop job.",
      "If level is low, measure pads and look for wet calipers/lines before you just fill it.",
    ],
  }),
  ch({
    id: "fluids.washer",
    section: "1. Fluids",
    title: "Washer fluid",
    lede: "Blue cap in the engine bay. Front and rear washers must both throw fluid — you confirm spray later with the wipers.",
    factory: "Any washer fluid rated for the climate. Do not pour coolant or plain water in and leave it in winter.",
    requires: "Bottle not empty. Both nozzles wet the glass. Rear hatch washer works.",
    measure: "Look in the translucent bottle or dip. Key ON, spray front and rear. Note clogs.",
    good: "Fluid present. Both fronts and the rear spray. No cracked bottle.",
    fail: "Empty, frozen, or no spray from a nozzle. Clear the jet or refill before a road test in dirty weather.",
    steps: [
      "Find the blue-cap bottle. Confirm fluid is visible.",
      "Top with washer fluid if low.",
      "Key ON, spray front and rear. Aim the jets at the glass, not the roof.",
    ],
  }),
  ch({
    id: "fluids.transferSeep",
    section: "1. Fluids",
    title: "Transfer case seep (4WD)",
    lede: "Not a dipstick. 30k service item on 4WD Armadas. Check seepage every visit; check level on the 30k.",
    factory:
      "Nissan Matic D, about 3.0 L / 3⅛ qt. Change every 30,000 miles. Fill to the fill-plug hole, truck level.",
    requires: "Seals dry enough that you cannot wipe a fresh wet finger. Level at the fill hole on a 30k. 2WD trucks skip this.",
    measure:
      "After a drive, flashlight on the transfer case (behind the transmission, 4WD). Look at output seals and the pan/cover. For level: fill plug out (upper plug, not the drain). Oil should wet your finger at the hole.",
    good: "Dry seals. Gear-oil/ATF look, not milky, not glitter. Level at the hole.",
    fail: "Fresh wetness at the seals. Milky (water). Glitter. Low: fill Matic D and find the leak. Do not confuse transfer seep with trans-pan ATF.",
    steps: [
      "Confirm 4WD. 2WD: mark N/A.",
      "Park level after a drive. Flashlight on the transfer case seals.",
      "On a 30k: fill plug out, finger at the hole, smell and color.",
      "Photograph wetness. Fill only with Matic D.",
    ],
  }),
  ch({
    id: "fluids.frontDiffSeep",
    section: "1. Fluids",
    title: "Front differential seep (4WD)",
    lede: "Front axle housing on 4WD. 30k fluid. Seepage at the cover or axle seals is the visit check.",
    factory: "API GL-5 80W-90 (synthetic 75W-90 is acceptable for heat and noise). Front about 1.6 L / 3⅜ pt. Change every 30,000 miles.",
    requires: "Truck level. No active drip. Fill to the fill-plug hole on a 30k. 2WD skips this.",
    measure:
      "Flashlight on the front diff cover, axle seals, and vent. For level: upper fill plug out. Oil at or just below the hole.",
    good: "Dry enough. Gear oil looks like gear oil — not milky, not glitter-heavy, not burnt tar.",
    fail: "Active drip. Milky (water). Heavy glitter. Cover bolts weeping a stream.",
    steps: [
      "4WD only. After a drive, look at the front housing and axle seals.",
      "30k: fill plug out, finger wet at the hole, smell it.",
      "Refill GL-5 80W-90 to the hole. Photograph seepage.",
    ],
  }),
  ch({
    id: "fluids.rearDiffSeep",
    section: "1. Fluids",
    title: "Rear differential seep",
    lede: "Cover and pinion seal. Rear diffs on these can whine (TSB NTB05-069). Whine plus glitter is not “just refill.”",
    factory: "API GL-5 80W-90 (synthetic 75W-90 acceptable). Rear about 1.75 L / 3¾ pt. Change every 30,000 miles.",
    requires: "No active drip at the cover or pinion. Level at the fill hole on a 30k. Pinion seal dry.",
    measure:
      "Flashlight on the rear cover gasket and the pinion seal (yoke). Wipe. For level: upper fill plug, truck level, oil at the hole. Note pinion Y/N on the checklist.",
    good: "Dry pinion and cover. Oil at the hole. No heavy glitter, not milky, not burnt.",
    fail: "Wet pinion seal, dripping cover, milky oil, glitter plus whine — do not just refill. Schedule seal/rebuild diagnosis.",
    steps: [
      "After a drive, look at the rear cover and the pinion yoke.",
      "Mark pinion seal Y/N. Photograph wetness.",
      "30k: fill plug out, finger at the hole, smell and color.",
      "If it whines and the magnet/oil has glitter, stop treating it as a fluid-only job.",
    ],
  }),
  ch({
    id: "engine.timingCover",
    section: "2. Engine bay",
    title: "Cold-start noise — timing cover",
    lede: "VK56 timing chain. You are listening at the front of the engine on a COLD start. Do not rev it.",
    factory:
      "Short rattle 1–3 seconds then gone is common (chain/tensioner taking up slack). Ongoing rattle is worn tensioner or guides — TSB NTB05-084a territory. Confirm any repair against FSM SM5E-1T60U1.",
    requires: "Cold engine. Idle only. Record seconds and whether it dies or keeps going.",
    measure:
      "Phone ready at the front bumper. Key ON, start, idle. Walk to the timing cover (front of the engine). Listen 15–20 seconds. Write quiet / short rattle / ongoing rattle and seconds.",
    good: "Quiet, or a short 1–3 sec rattle that is the same every morning and then gone.",
    fail: "Rattle that keeps going. Rattle that grows visit to visit. Ongoing rattle plus a low oil-pressure note or lamp is do-not-drive — Pass is blocked. Budget a timing set. Do not ignore it.",
    steps: [
      "Engine COLD. Do not rev.",
      "Key to ON — watch dash prove-out. Start. Idle.",
      "Stand at the front bumper 15–20 seconds, then each wheel well.",
      "Log seconds. Short then gone: watch. Ongoing: plan the timing set. Write oil pressure in the green or low / lamp. Ongoing plus low oil pressure cannot be a Pass.",
    ],
  }),
  ch({
    id: "engine.manifolds",
    section: "2. Engine bay",
    title: "Cold-start noise — exhaust manifolds",
    lede: "Exhaust-manifold cracks are very common on the VK56. Tick plus soot at the flange gets scheduled.",
    factory:
      "No “allowed crack.” A black sooty stripe at the manifold-to-head flange means a crack or blown gasket. Cold-only tick with no soot can wait a short while. Soot plus tick gets scheduled.",
    requires: "Listen cold. After warmup, look at both bank flanges for soot. Write L / R / both and soot Y/N.",
    measure:
      "Tick is louder cold, one bank — left or right cylinder head / manifold, not the timing cover. After it warms, flashlight on each manifold-to-head flange.",
    good: "Quiet after warmup. No soot stripe.",
    fail: "Tick that stays plus soot: schedule manifolds/gaskets. Do not confuse this with a chain rattle (front cover).",
    steps: [
      "On the cold start, walk each side of the engine. Note L, R, or both.",
      "After warmup, look at each flange. Black sooty stripe = leak.",
      "Photograph soot. Schedule if tick + soot.",
    ],
  }),
  ch({
    id: "engine.idle",
    section: "2. Engine bay",
    title: "Idle quality",
    lede: "Still in the driveway. Smooth idle, CEL off after prove-out. Hunting idle is a find-it-now, not a road-test problem.",
    factory:
      "Oil pressure lamp OFF within a second or two. Charge lamp OFF. AT check, ABS, SLIP, VDC, CEL off after prove-out. Idle smooth, not hunting. Temp gauge climbs slowly from cold — must not jump to hot.",
    requires: "Idle in Park, engine running. No new lamps. Write smooth/rough and CEL on/off.",
    measure: "Watch the dash after start. Feel the mirror/steering. Listen for knock (deeper, does not go away) vs a little cam/chain tick that fades.",
    good: "Smooth idle. All prove-out lamps off. Temp climbing slowly.",
    fail: "Rough, hunting, shaking the mirror. CEL stays on — scan before the road test. Knock: stop. Temp jumping to hot: stop.",
    steps: [
      "Key ON — lamps prove out. Start. Do not rev.",
      "Confirm oil and charge lamps go out immediately.",
      "Note idle quality and CEL.",
      "If any lamp stays on, scan codes before you pull out.",
    ],
  }),
  ch({
    id: "engine.belt",
    section: "2. Engine bay",
    title: "Serpentine belt",
    lede: "One belt drives the front accessories. Glaze, fray, missing chunks, or a floppy tensioner get replaced — belt and tensioner together if noisy.",
    factory:
      "Replace the belt when cracked, glazed, frayed, or down to the cords. Tensioner play is not “watch it.” Confirm part numbers in the FSM. Typical 60k look on an aged belt.",
    requires: "Ribs intact. No glaze. Tensioner not flopping. No squeal on start.",
    measure:
      "Engine off. Twist the belt to see the ribs and the back. Push the tensioner arm — it should be firm, not sloppy. After start, listen for squeal.",
    good: "OK: no cracks, no glaze, no fray, tensioner quiet and firm.",
    fail: "Cracks, glaze, fray, cords showing, squeal, tensioner play. Replace belt and tensioner together if glazed or noisy.",
    steps: [
      "Engine off. Inspect the full length — ribs and back.",
      "Check tensioner play by hand.",
      "Start and listen for squeal.",
      "Photograph cracks/glaze. Do not dress a glazed belt with goop.",
    ],
  }),
  ch({
    id: "engine.radiator",
    section: "2. Engine bay",
    title: "Radiator tanks, seams, hoses",
    lede: "Plastic tanks on this radiator crack at the seams. Two small metal lines into the tank are ATF cooler lines — not heater hoses. Engine cold for the first look.",
    factory:
      "Hoses firm, not mushy, not rock-hard. Tanks not split. No seep at upper/lower seams or hose clamps. Never open the cap hot. Cooling system 14.4 L / 3¾ gal 50/50 Nissan LL.",
    requires: "Dry clamps. Plastic not split. Hoses that still squeeze like rubber. ATF ports dry (see ATF cooler lines if wet).",
    measure:
      "Squeeze upper and lower radiator hoses and heater hoses. Look at top and bottom tank seams. Look at the two small ATF lines into the tank. After a drive, look again for wetness.",
    good: "Hoses dry at the clamps, firm. Tanks dry. No swollen spots.",
    fail: "Soft hoses get replaced, not “watched.” Split plastic, seeping seams, or wet ATF ports. Overheat later in the drive: stop.",
    steps: [
      "Engine cold. Squeeze the big hoses. Photograph seams.",
      "Find the two small ATF cooler lines. If wet or pink, treat as SMOD risk — open the ATF cooler-lines how-to.",
      "After the drive, recheck for fresh wetness. Do not open the cap hot.",
    ],
  }),
  ch({
    id: "engine.atfLines",
    section: "2. Engine bay",
    title: "ATF cooler lines at radiator",
    lede: "The 2005 Armada radiator has a small ATF cooler built in. When that chamber cracks, coolant and ATF mix and kill the RE5R05A. This is the SMOD check.",
    factory:
      "Those two small metal/rubber lines dump ATF heat into the radiator. A bypass reroutes them to an external stacked-plate cooler (or factory auxiliary plus an added cooler) and caps the radiator ATF ports. Highest-value job on a 2005 that still shifts. After bypass: idle, shift, HOT ATF recheck, leak look, short road test.",
    requires:
      "ATF red/amber on the stick. Coolant not oily. Those two fittings dry. If any of the three is wrong, treat as SMOD. Pink/milky/sweet ATF: do not bypass-and-drive — valve body/TCM may already be ruined.",
    measure:
      "They are not heater hoses. Follow one from the transmission and one returning. Look at the fittings where they enter the radiator. Wet, rusty, or stained = leaking. After a drive, feel carefully for oily wetness.",
    good: "Still connected (unless a proper bypass is already done). Fittings dry. No pink residue. Bypass-done Y only if the radiator ports are capped and an external cooler is actually installed.",
    fail: "Wet fittings, pink residue, oily coolant, or milky ATF. Park it. Do not keep driving it to finish the week. Bypass is for a truck that still shifts with clean ATF.",
    steps: [
      "Find the two small lines into the radiator tank. Photograph the fittings.",
      "Note connected Y/N, wet fittings Y/N, bypass already done Y/N.",
      "Cross-check ATF color/smell and coolant sheen.",
      "If mixed: stop. Diagnosis, likely rebuild/reman — not “bypass and hope.”",
    ],
  }),
  ch({
    id: "engine.airFilter",
    section: "2. Engine bay",
    title: "Air filter",
    lede: "Engine air box, clamps, passenger or center-forward. Cabin filter is behind the glove box on most of these — 15k visit.",
    factory: "Replace rather than tap-clean if packed. Cabin filter on the 15k. Oil-soaked paper is blow-by / PCV, not “a dirty filter.”",
    requires: "Pleats visible, not caked. No oil soaking. Cabin due Y/N written.",
    measure: "Unclip the air-box lid. Lift the filter. Hold it up to the sky. Cabin: drop the glove-box door per the owner’s manual, slide the filter out.",
    good: "Clean, or dirty enough to note but not blocking. Cabin not overdue if this is a 15k.",
    fail: "Packed, wet with oil, torn. Replace. Find PCV if it is oily.",
    steps: [
      "Unclip the box. Hold the element to the sky.",
      "Note clean / dirty / replace. Photograph if dirty.",
      "15k: cabin filter behind the glove box.",
    ],
  }),
  ch({
    id: "engine.battery",
    section: "2. Engine bay",
    title: "Battery",
    lede: "Top posts in the engine bay. Age plus night-shift sits kill these. A load test is the honest test.",
    factory:
      "Resting after shutdown overnight typically 12.4–12.7 V. Running typically 13.5–14.7 V. Tight, clean posts. No cracked case. Load test at a parts store at this age.",
    requires: "Write rest V, running V, terminals clean Y/N, load test pass/fail.",
    measure:
      "Engine off: rest voltage across posts. Wiggle cable ends — white/green crust is corrosion. After start: running voltage. Load test if rest is low or cranking is slow.",
    good: "Rest 12.4–12.7 V. Running 13.5–14.7 V. Tight clean posts. Load test pass.",
    fail: "Rest below ~12.2 V, running below ~13.3 or above ~15, corroded terminals, cracked case, load-test fail, slow crank. Clean/repair/replace before you strand it.",
    steps: [
      "Engine off. Measure rest V. Photograph terminals.",
      "Wiggle the clamps. Clean if crusty.",
      "Start. Measure running V.",
      "Load test if in doubt. Do not clear a no-crank as “just the stick.”",
    ],
  }),
  ch({
    id: "engine.grounds",
    section: "2. Engine bay",
    title: "Ground straps",
    lede: "Block-to-chassis and body. Corroded grounds on this chassis mimic sensor and charge problems.",
    factory: "Tight, clean metal-to-metal. No broken strands. No paint under the lug.",
    requires: "Write tight or corroded. Both engine and body straps.",
    measure: "Find the braided/flat straps at the block and body. Wiggle. Look under the lug for rust/paint.",
    good: "Tight, clean, intact braid.",
    fail: "Green crust, broken braid, loose lug. Clean or replace. Do not ignore a random electrical ghost until grounds are proven.",
    steps: [
      "Locate block-to-chassis and body grounds.",
      "Wiggle. Photograph corrosion.",
      "Clean to bare metal and retighten if corroded.",
    ],
  }),
  ch({
    id: "engine.pcv",
    section: "2. Engine bay",
    title: "PCV hose / vacuum lines",
    lede: "Cracked or oily PCV on a VK56 is blow-by and a dirty intake, not a “hose only” story if the filter is oil-soaked.",
    factory: "Hoses intact, not collapsed, not soaked in oil. PCV valve rattles if it is the removable type. Replace cracked hose — do not tape it.",
    requires: "OK / cracked / oily written. Vacuum lines seated.",
    measure: "Follow the PCV hose from the valve cover / intake. Squeeze. Look for oil inside the air box. Tug vacuum lines at the intake.",
    good: "OK: seated, not cracked, not oily.",
    fail: "Cracked, collapsed, oily, or off the nipple. Hiss at idle: find the leak now. Oil in the air filter: PCV/blow-by.",
    steps: [
      "Engine off. Trace PCV and nearby vacuum lines.",
      "Note cracked or oily. Photograph.",
      "Reseat or replace. Do not leave a hiss for a week “to see.”",
    ],
  }),
  ch({
    id: "engine.scan",
    section: "2. Engine bay",
    title: "Scan tool",
    lede: "Any OBD-II reader that shows codes is enough. Write stored and pending BEFORE you clear anything. ATF temp helps the HOT dipstick.",
    factory:
      "Do not clear codes until they are written down. AT check / CEL / ABS / SLIP / VDC that stay on after prove-out get scanned before the road test. Factory ATF HOT check is near 149°F (65°C).",
    requires: "Stored codes, pending codes, ATF temp written.",
    measure: "Plug in under the dash. Record stored and pending. If the tool reads ATF temp, write it for the dipstick check.",
    good: "No stored, no pending, or known-old codes already diagnosed. ATF temp in the HOT window when you read the stick.",
    fail: "New stored codes, pending that return, lamps that stay on. Stop and diagnose before the road test. Do not clear and hope.",
    steps: [
      "Key ON or engine running per the tool.",
      "Write stored and pending. Photograph the screen.",
      "Note ATF temp if shown. Use it when you pull the trans stick.",
      "Do not clear until the report is done.",
    ],
  }),
  ch({
    id: "trans.parkReverse",
    section: "3. Transmission",
    title: "Park → Reverse engagement",
    lede: "RE5R05A. Do this cold and again after a 15-minute drive. Skip the whole drive if ATF is pink, milky, or sweet.",
    factory: "Takes gear in about a second. Mild bump is OK. Long delay, bang, or grinding is not. Level ground, foot on the brake, idle.",
    requires: "Cold and hot both circled: Good / Delay / Bang. Do not continue if ATF is rejected.",
    measure: "From a complete stop, brake on, shift P → R. Count the beat until it takes. Repeat after the drive when hot.",
    good: "Good: takes in about a second, mild bump.",
    fail: "Delay or bang, worse hot than cold. That is a failing unit — not a “fluid top.”",
    steps: [
      "Confirm ATF is not pink/milky/sweet. If it is, lock the road test.",
      "Level, brake on, idle. P → R. Feel the take-up.",
      "Log cold. Repeat hot after 15 min. Write notes.",
    ],
  }),
  ch({
    id: "trans.reverseDrive",
    section: "3. Transmission",
    title: "Reverse → Drive",
    lede: "Same standard as Park → Reverse. Delay or bang that grows as it heats up is a fail.",
    factory: "Takes gear in about a second, mild bump OK. Delay or bang is not.",
    requires: "Cold and hot: Good / Delay / Bang.",
    measure: "Brake on, idle, R → D. Feel the take-up. Repeat hot.",
    good: "Good, both temperatures.",
    fail: "Delay or bang, especially worse hot.",
    steps: [
      "Brake on, idle. R → D.",
      "Log cold and hot. Do not power-brake it to “test.”",
    ],
  }),
  ch({
    id: "trans.up12",
    section: "3. Transmission",
    title: "1–2 upshift",
    lede: "Light throttle from a stop on a quiet road. Cold 1–2 is often a little firmer than hot 1–2 — that by itself is not a failed transmission.",
    factory: "One clean step. No roar of rpm without movement (flare). No slam.",
    requires: "Cold and hot: Clean / Flare / Harsh.",
    measure: "From a complete stop, light throttle. Feel 1–2. Flare = rpm jumps before it grabs.",
    good: "Clean. Slightly firmer cold is OK.",
    fail: "Flare, slam, or miss. Flare that gets longer as it heats up is a failing unit.",
    steps: [
      "Quiet road. Light throttle from a stop.",
      "Feel 1–2. Log cold and after the drive, hot.",
    ],
  }),
  ch({
    id: "trans.up23",
    section: "3. Transmission",
    title: "2–3 upshift",
    lede: "Same standard as 1–2. One clean step, no flare, no slam.",
    factory: "Clean step. Flare or harsh is not acceptable.",
    requires: "Cold and hot: Clean / Flare / Harsh.",
    measure: "Continue the light-throttle pull. Feel 2–3. Then a little more throttle on a second run.",
    good: "Clean both temperatures.",
    fail: "Flare, slam, miss.",
    steps: [
      "Light throttle through 2–3. Repeat with a bit more throttle.",
      "Log cold and hot.",
    ],
  }),
  ch({
    id: "trans.up345",
    section: "3. Transmission",
    title: "3–4 and 4–5",
    lede: "Quiet fifth at cruise. Missing 5th is a fail on this 5-speed.",
    factory: "Quiet fifth. Clean 3–4 and 4–5. Hunt or miss is not.",
    requires: "Cold and hot: Clean / Miss / Hunt.",
    measure: "Build speed on a quiet road. Feel 3–4 and 4–5. Cruise and see that 5th holds.",
    good: "Clean, quiet fifth.",
    fail: "No 5th, hunt between gears, miss.",
    steps: [
      "Light then moderate throttle up through the gears.",
      "Confirm 5th holds on cruise. Log cold and hot.",
    ],
  }),
  ch({
    id: "trans.tcc",
    section: "3. Transmission",
    title: "TCC lock ~45–60 mph light throttle",
    lede: "Torque-converter clutch. Gentle lock around 45–60 mph with a light foot. Shudder like rumble strips is the classic RE5R05A complaint — fluid/cooler first, then diagnosis.",
    factory: "Smooth lock. Slip (rpm rises at the same speed) or shudder is not. Skip if ATF is rejected.",
    requires: "Cold and hot: Smooth / Shudder / Slip.",
    measure: "Cruise 45–60 mph, gentle foot. Feel a slight lock. Shudder = rumble-strip vibration under a light foot.",
    good: "Smooth lock, both temperatures (often clearer hot).",
    fail: "Shudder or slip. Do not keep driving it hard. ATF condition and cooler/bypass first, then a shop that knows this trans.",
    steps: [
      "Quiet road, 45–60 mph, light throttle.",
      "Feel lock. Log shudder/slip. Recheck ATF if it shudders.",
    ],
  }),
  ch({
    id: "trans.kickdown",
    section: "3. Transmission",
    title: "Kickdown 5–4 / 4–3",
    lede: "Passing-speed kickdown. It should downshift and pull — not hesitate in a tall gear or slam.",
    factory: "Clean downshift and pull. Late or harsh is not.",
    requires: "Cold and hot: Clean / Late / Harsh.",
    measure: "At cruise, press through the kickdown. Feel 5–4 / 4–3. Repeat hot.",
    good: "Clean, pulls.",
    fail: "Hesitates, stays in a tall gear, or slams.",
    steps: [
      "Safe passing lane. Kickdown once cold if you must, then properly hot.",
      "Log clean / late / harsh.",
    ],
  }),
  ch({
    id: "trans.fourwd",
    section: "3. Transmission",
    title: "4WD engage / disengage",
    lede: "If equipped. Use 4H only on dirt or a loose surface — 4H on dry pavement will bind and feel like a driveline problem that is not there.",
    factory: "Engages and returns to 2H. Binds on pavement if you test it there — that is the test method failing, not the transfer case.",
    requires: "Works / Binds / No. 2WD: mark N/A.",
    measure: "Loose surface. 2H → 4H → back. Listen for clunks. Do not force it at speed.",
    good: "Works, no bind on a loose surface.",
    fail: "Will not engage, stays bound, grinding. Diagnose transfer case / actuator / hubs. Do not test 4H on dry pavement and call it a fail.",
    steps: [
      "2WD truck: N/A.",
      "Loose dirt/gravel only. Shift 4H, drive a few yards, return to 2H.",
      "Log works / binds / no.",
    ],
  }),
  ch({
    id: "trans.atfReject",
    section: "3. Transmission",
    title: "ATF reject condition",
    lede: "STOP if pink, milky, or sweet-smelling. That is coolant in the transmission. Do not continue the drive. Do not call the truck a Pass.",
    factory:
      "Pink / milky / strawberry / sweet = SMOD. Park it. Do not bypass-and-drive. Valve body and internal TCM may already be ruined. That is a diagnosis and likely a rebuild or reman conversation.",
    requires: "If ATF color is pink or milky, or smell is sweet: check this box, lock Section 3 and the road test, overall cannot be Pass.",
    measure: "The paper from the HOT dipstick. Color and smell. Coolant reservoir oil film is the other direction of the same leak.",
    good: "Not rejected. ATF red/amber, smells like ATF.",
    fail: "Rejected. Do not drive it to finish the week. Write it on the result line.",
    steps: [
      "Read the ATF how-to first. Look at the paper.",
      "Pink, milky, or sweet: check reject, acknowledge STOP, skip the road test.",
      "Photograph the stick and the paper. Do not add Dexron, Mercon, or anything except Matic J/S — and do not add those to milky fluid to “see.”",
    ],
  }),
  ch({
    id: "brakes.pads",
    section: "4. Brakes & rolling",
    title: "Pad thickness",
    lede: "Measure remaining friction material, not the steel backing. Wheel off is best. Through the wheel you can often see the outer pad.",
    factory:
      "Nissan BR for this platform: lining new about 12.0 mm (0.476 in). Repair limit 1.0 mm (0.039 in). Do not run them to the indicator grind. Write LF / RF / LR / RR in mm. Confirm in FSM SM5E-1T60U1 before you machine or replace.",
    requires: "A number in mm at each corner on a 15k/30k/baseline. Visual on an oil-change short check. Honest material left. Next visit compares vs last and the miles between — that is how a sticking caliper shows up before the rotor is scrap.",
    measure:
      "Brake pad gauge or steel rule on the friction material only. Inner pad is often thinner — look inboard with a light, or pull the wheel. Do not measure the backing plate. Write LF / RF / LR / RR so the next report can compute wear rate.",
    good: "Well above 1.0 mm, even inner/outer, no taper to the grind tab. Shop practice: schedule before you are staring at the limit.",
    fail: "At or near 1.0 mm, grind tab contacting, inner pad gone, wet with brake fluid. Replace as an axle set. Do not mix thicknesses on the same axle.",
    steps: [
      "Chock, jack stands on the frame if the wheel comes off.",
      "Measure remaining lining at each corner. Write mm.",
      "Photograph the thinnest pad. Note inner vs outer.",
      "If one corner of an axle dropped much more than the other since last visit, treat it as a sticking caliper until proven otherwise.",
    ],
  }),
  ch({
    id: "brakes.rotors",
    section: "4. Brakes & rolling",
    title: "Rotors",
    lede: "Thickness, rust lip, grooves, pulse on a stop. Front discs on the 2005 brake system are a two-millimeter window from new to minimum.",
    factory:
      "2005 brake system: front disc standard thickness 28.0 mm (1.10 in), minimum 26.0 mm (1.02 in). Rear disc standard 14.0 mm (0.551 in), repair limit 12.0 mm (0.472 in) per FSM SM5E-1T60U1 SDS. Do not machine below the stamp. Grooves you can catch a fingernail in, or a huge rust lip, fail even if thickness is legal.",
    requires: "Write front and rear thickness / condition. Pulse on stop is a rotor/hub issue until proven otherwise.",
    measure:
      "Micrometer at the thinnest swept face, not the rust lip. Compare to the MIN stamp on the hat. Feel a 30 and 60 stop later for pulse.",
    good: "Above MIN, no fingernail grooves, no huge rust lip, no pulse.",
    fail: "At or below MIN, deep grooves, lip that the pad is riding, pulse, heat cracks. Replace. Do not “cut to nothing.”",
    steps: [
      "Wheel off is honest. Measure thickness. Read the MIN stamp.",
      "Run a fingernail across the swept face. Look at the rust lip.",
      "Write F and R. Photograph lips/grooves.",
      "Confirm pulse on the road-test stops.",
    ],
  }),
  ch({
    id: "brakes.hoses",
    section: "4. Brakes & rolling",
    title: "Brake hoses & lines",
    lede: "This checklist line is the caliper inspection on the 2005 Armada: rubber hoses, steel lines, and the caliper at each corner. A wet caliper is a leak — not dusty film.",
    factory:
      "Hoses not cracked, not swollen, not leaking at the crimp. Caliper dry at the piston dust boot, slide-pin boots, and banjo bolt. Slide pins move by hand with a smear of brake grease — they must not be seized. Piston boot intact, not torn, not ballooned. Steel lines along the frame not scabbed through. Pad backing plates dry — wet backing is a leaking caliper, not just worn pads. Front rotor new 28.0 mm (1.10 in), minimum 26.0 mm (1.02 in). Pad lining new about 12.0 mm, repair limit 1.0 mm (0.039 in) — those numbers live on the pad and rotor lines; a wet caliper makes those readings a fail even if thickness is legal. Confirm flare-nut and caliper-bolt torque in FSM SM5E-1T60U1. Do not guess.",
    requires:
      "Write hose/line condition. Wet caliper Y/N at every corner you can see. Any fresh wetness is a fail until the source is proven. Do not drive a leaking brake circuit.",
    measure:
      "Chock. Jack stands on the frame if the wheel comes off — never crawl under a scissor jack. One corner at a time: flashlight on the hose from body to caliper, the steel line in the inner fender, the caliper piston dust boot, both slide-pin boots, and the banjo. Squeeze the hose — a bulge is a fail. Wipe the caliper body and the boot — fresh DOT 3 vs dusty film. Push the slide pins. Look at the inboard pad backing for wetness. Repeat LF / RF / LR / RR.",
    good: "Dry calipers. Pins slide. Boots intact. Hoses flexible, no cracks, no bulge. Lines solid. Wet caliper N.",
    fail: "Cracked or bulged hose. Wet caliper, wet banjo, torn piston boot, seized pins, rusted-through line, fluid on the pad backing. Replace hose / caliper / line as required. Do not clamp a bulge. Do not keep adding fluid to a wet corner.",
    searchExtra: "caliper calipers piston boot slide pin pins banjo dust boot wet caliper brake hose",
    steps: [
      "Park level. Parking brake on. Chock the opposite wheel. If the wheel comes off, stands on the frame.",
      "Start at LF. Follow the rubber hose from the body bracket to the caliper. Look for cracks, wetness at the crimp, and a bulge when you squeeze.",
      "Look at the caliper: piston dust boot, slide-pin boots, banjo bolt. Wipe — fresh fluid is a fail. Dusty film is a note.",
      "If the wheel is off, push the slide pins. They must move. A seized pin tapers the pads — see pad thickness on this visit.",
      "Repeat RF, LR, RR. Write wet caliper Y/N. Photograph any wet boot, bulge, or scabbed line.",
      "If any corner is wet, check pad/rotor contamination and the master-cylinder level before you add fluid.",
    ],
  }),
  ch({
    id: "brakes.master",
    section: "4. Brakes & rolling",
    title: "Master cylinder / booster",
    lede: "Firewall, driver’s side. Seepage at the master into the booster is how you get a disappearing pedal and a dead vacuum booster.",
    factory: "No seepage at the master. Pedal firm with the engine running. Booster: engine running, pedal assist present. Confirm any replacement against the FSM.",
    requires: "Seepage Y/N. Pedal firm Y/N.",
    measure:
      "Look at the master-to-booster seam and the reservoir. Engine running, press the pedal — it should be firm, not sinking. Engine off vs running: booster should make the pedal easier running.",
    good: "Dry master. Firm pedal. Booster assists.",
    fail: "Wet seam, sinking pedal, no assist, reservoir crusted with fluid. Do not drive it. Master/booster is a paired conversation if fluid has entered the booster.",
    steps: [
      "Wipe and look at the master/booster seam.",
      "Engine running: firm pedal, no sink.",
      "Photograph seepage. Do not keep adding fluid to a wet master.",
    ],
  }),
  ch({
    id: "brakes.pedalHeight",
    section: "4. Brakes & rolling",
    title: "Pedal height engine running",
    lede: "Factory figure is remaining pedal, not “how far you push.”",
    factory:
      "With the engine running, distance from pedal top to floor under a hard push should still have pedal left — 3.5 in (90 mm) or more remaining under 110 lb. Write the measured remaining height.",
    requires: "Engine running. Measured number. Spec ≥ 3.5 in @ 110 lb.",
    measure:
      "Engine idling. Press the pedal hard (~110 lb — a firm two-foot shop press). Measure from the pedal pad down to the floor (remaining height). Do not measure travel from the released position unless you also know the released height.",
    good: "≥ 3.5 in remaining, firm, no sink.",
    fail: "Less than 3.5 in remaining, sinking, spongy. Air, leak, or master. Do not road-test a short/sinking pedal hard.",
    steps: [
      "Engine running. Firm press.",
      "Measure remaining height to the floor. Write it.",
      "If short or sinking, find fluid loss or air before the 60 mph stop.",
    ],
  }),
  ch({
    id: "brakes.parking",
    section: "4. Brakes & rolling",
    title: "Parking brake",
    lede: "Pedal-type park brake on this truck. Count clicks from fully released.",
    factory: "About 3–4 clicks at 44 lb. Must hold on a grade. Write clicks and holds-on-grade Y/N.",
    requires: "3–4 clicks at a firm push. Holds the truck on a grade. Fully releases (no drag).",
    measure:
      "Fully release. Press the park-brake pedal and count clicks at a firm push (~44 lb). Then on a grade (or a restrained stall), set it and see if it holds. Drive a few feet released — no drag.",
    good: "3–4 clicks, holds, no drag released.",
    fail: "Goes to the floor, 1 click, 8 clicks, does not hold, or drags. Adjust or repair. Do not leave a dragging park brake — it cooks rear pads.",
    steps: [
      "Fully released. Count clicks at a firm press. Write the number.",
      "Hold-on-grade test. Release and confirm no drag.",
    ],
  }),
  ch({
    id: "brakes.absLamps",
    section: "4. Brakes & rolling",
    title: "ABS / SLIP / VDC lamps",
    lede: "Prove-out then off. Stay-on or intermittent is a scan item before you call brakes “fine.”",
    factory: "ABS, SLIP, and VDC prove out at key ON / start, then go OFF. A lamp that stays on is a stored fault. Do not clear until written.",
    requires: "Prove-out then off / stay on / intermittent.",
    measure: "Key ON, watch the cluster. After start, they must go out. Note flicker on the drive.",
    good: "Prove-out then off. Stay off on the drive.",
    fail: "Stay on or intermittent. Scan ABS codes. Do not road-test as a pass with ABS dark-failed.",
    steps: [
      "Key ON — watch prove-out.",
      "After start, confirm they go out.",
      "If they stay on, scan and write codes. Do not clear first.",
    ],
  }),
  ch({
    id: "brakes.tread",
    section: "4. Brakes & rolling",
    title: "Tires tread",
    lede: "All four plus the spare. Inner edge of the fronts is where Armadas hide wear — crouch and look.",
    factory:
      "Replace before cords. Even wear across the face. US legal minimum is 2/32 in in the grooves; do not run an SUV there. Inner-shoulder wear on the fronts means alignment or upper control arms — do not ignore it.",
    requires: "Write LF / RF / LR / RR / spare. Tread even. No cords, bulges, or cracks. Next visit compares vs last and miles between — alignment / UCA show up as one side going faster.",
    measure: "Tread gauge in the main grooves, not the wear bars only. Check inner and outer. Spare too.",
    good: "Honest tread, even, spare usable.",
    fail: "Cords, 2/32 or less, inner shoulder gone, spare flat/missing. Schedule tires/alignment/UCAs as the wear pattern says.",
    steps: [
      "Gauge each tire including the spare. Write the numbers.",
      "Crouch and look at the front inner shoulders.",
      "If one side of an axle lost 2/32 more than the other since last visit, treat it as alignment or UCA until proven otherwise.",
    ],
  }),
  ch({
    id: "brakes.tireAge",
    section: "4. Brakes & rolling",
    title: "Tire age (DOT week/year)",
    lede: "Four-digit DOT date on the sidewall. Example 2319 = 23rd week of 2019. Tires older than 6–7 years get replaced even with tread.",
    factory: "Replace at 6–7 years regardless of tread. Write week/year for each corner and the spare. Spare is often the oldest.",
    requires: "DOT week/year written. Age, not just tread.",
    measure: "Find DOT on the sidewall (sometimes only on the inner side). Last four digits: WWYY.",
    good: "Under ~6–7 years, all five.",
    fail: "Older than 6–7 years, unreadable DOT, spare from a different decade. Replace even with tread.",
    steps: [
      "Read DOT on each tire and the spare. Write WWYY.",
      "If you must crawl to see the inner stamp, do it. Photograph.",
    ],
  }),
  ch({
    id: "brakes.wear",
    section: "4. Brakes & rolling",
    title: "Tire wear pattern",
    lede: "Even / inner shoulder / outer / cupping / center. Pattern tells you alignment, UCAs, pressure, or balance.",
    factory:
      "Even across the face. Inner-shoulder wear on the fronts = alignment or upper control arms. Center wear = overinflation. Outer = underinflation or aggressive cornering. Cupping = balance/shocks.",
    requires: "One pattern call, plus notes if corners disagree.",
    measure: "Look and feel inner and outer of each front. Compare rears.",
    good: "Even wear across the face on all four, matching the wear-pattern call.",
    fail: "Inner, outer, cupping, center. Do not just buy tires without fixing UCAs/alignment if the inner shoulder is gone.",
    steps: [
      "Feel inner fronts. Look at rears.",
      "Circle the pattern. Photograph inner wear.",
      "If inner fronts, plan alignment and UCA inspection.",
    ],
  }),
  ch({
    id: "brakes.pressures",
    section: "4. Brakes & rolling",
    title: "Pressures including spare",
    lede: "Cold. Driver’s-door sticker, not the number on the tire.",
    factory: "Set to the door-jamb placard for the 2005 Armada (load and tire size on that sticker). Spare has its own number on the sticker. Measure cold.",
    requires: "Write LF / RF / LR / RR / spare. Match the door sticker.",
    measure: "Quality gauge, cold, all five. Compare to the driver’s-door sticker.",
    good: "All five at the sticker. Caps on.",
    fail: "20% low, spare forgotten, set to the sidewall max. Reset to the door sticker.",
    steps: [
      "Read the door sticker first.",
      "Gauge all five cold. Write the numbers. Set to spec.",
    ],
  }),
  ch({
    id: "brakes.lugTorque",
    section: "4. Brakes & rolling",
    title: "Lug torque after rotation",
    lede: "After any wheel-off or rotation, torque in a star pattern. Then recheck after a short drive.",
    factory:
      "2005 Armada wheel nuts: 98 ft-lb (133 N·m). Star pattern, clean dry threads (no grease unless the FSM says otherwise). Recheck after 50–100 miles. Confirm in the owner’s manual / FSM if wheels were changed.",
    requires: "Torqued to spec after rotation or any wheel-off. Not “impacted until it sings.”",
    measure: "Click-type or beam torque wrench set to 98 ft-lb. Star pattern. All five wheels if you rotated, including the spare carrier if you pulled it.",
    good: "All lugs at 98 ft-lb, star, rechecked.",
    fail: "Unknown impact-only, missing lug, rounded nut, never rechecked. Do not leave the shop without a wrench click.",
    steps: [
      "If you did not pull wheels, mark N/A or confirm they were not loose.",
      "If you did: 98 ft-lb star. Recheck after the road test.",
      "Write it. Do not paint-pen a guess.",
    ],
  }),
  ch({
    id: "brakes.bearings",
    section: "4. Brakes & rolling",
    title: "Wheel bearings / hubs",
    lede: "Growl that changes with speed, or play at 12 and 6 with the wheel off the ground.",
    factory:
      "No perceptible rock in the hub with the wheel off the ground (12 and 6). No growl on the drive. Confirm hub nut torque in the FSM if you take a hub apart — do not guess that number.",
    requires: "Write LF / RF / LR / RR play or growl.",
    measure:
      "On stands, grab the tire at 12 and 6 and rock. A clunk here is bearing/ball joint — isolate with a pry. On the drive, growl that follows speed and changes in a turn is a hub.",
    good: "No play, no growl.",
    fail: "Rock in the hub, growl, heat at the cap after a drive. Replace the hub. Do not pack an old unit and call it good.",
    steps: [
      "Stands, 12-and-6 rock each corner. Write play.",
      "Road test: listen for growl. Note which side in a turn.",
    ],
  }),
  ch({
    id: "brakes.alignment",
    section: "4. Brakes & rolling",
    title: "Alignment feel",
    lede: "Tracks straight, small play only. Pull, wander, or inner front wear = alignment and likely UCAs on this chassis.",
    factory: "Straight on a level road, hands light. Dry-park wander plus inner front tire wear = upper control arms / alignment. Do not ignore inner shoulder wear.",
    requires: "Pull L / Pull R / Wander / Straight.",
    measure: "Level road, light grip. Does it walk? Brake in a straight line later for pull vs brake pull.",
    good: "Straight.",
    fail: "Pull, wander, or inner wear. Schedule alignment and inspect UCAs/ball joints/tie rods before you just buy tires.",
    steps: [
      "Level road, light hands. Note pull or wander.",
      "Pair with inner tire wear and the UCA/tie-rod checks.",
    ],
  }),
  ch({
    id: "steering.steeringPlay",
    section: "5. Steering / driveline",
    title: "Steering play at idle",
    lede: "Engine idling, lightly shake the wheel. Small play only. Clunk is a joint, not “character.”",
    factory: "Small play only. No clunk, no groan at full lock on the drive. Tracks straight.",
    requires: "Idle, Park or level ground, light shake. Note clunk or excess free play.",
    measure: "Engine idling. Lightly shake the steering wheel. Then full lock both ways on the drive — no groan that dumps PSF.",
    good: "Small play, no clunk.",
    fail: "Clunk, huge dead band, groan at lock (PSF/rack). Find tie rods, shaft U-joint, or rack.",
    steps: [
      "Idle. Light shake. Listen at the column and the rack.",
      "Full lock later on the drive. Check PSF if it groans.",
    ],
  }),
  ch({
    id: "steering.tieRods",
    section: "5. Steering / driveline",
    title: "Inner / outer tie rods",
    lede: "Wheels off the ground: grab the tire at 9 and 3. Inner and outer both fail on these.",
    factory: "No rock, no torn boot leaking grease. Replace as a pair on that side if the joint is loose. Alignment after.",
    requires: "No perceptible knock at 9 and 3. Boots intact.",
    measure: "Stands. 9 and 3 on each front tire. Have a helper watch the inner joint at the rack while you rock.",
    good: "Tight, boots intact.",
    fail: "Knock, torn boot, dry joint. Replace. Do not grease a torn boot and return it to service.",
    steps: [
      "Stands, 9-and-3 rock. Watch inner and outer.",
      "Photograph torn boots. Plan alignment after replacement.",
    ],
  }),
  ch({
    id: "steering.ballJoints",
    section: "5. Steering / driveline",
    title: "Upper & lower ball joints / UCAs",
    lede: "12 and 6 with the wheel off the ground. Upper control arms and ball joints are the inner-tire-wear story on this chassis.",
    factory: "No rock, no torn boot. Dry-park wander plus inner front wear = UCAs / alignment. Replace, then align.",
    requires: "No clunk at 12/6 that is the joint (not the hub). Boots intact.",
    measure:
      "Stands. 12 and 6. Isolate hub vs joint with a pry on the joint. Look at UCA bushings.",
    good: "Tight joints, decent UCA bushings.",
    fail: "Clunk, torn boot, collapsed UCA bushing, inner tire wear. Schedule UCAs/joints and alignment.",
    steps: [
      "12-and-6 rock. Pry the joint to separate hub play from ball-joint play.",
      "Look at UCA bushings. Photograph. Pair with inner tire wear.",
    ],
  }),
  ch({
    id: "steering.sway",
    section: "5. Steering / driveline",
    title: "Sway-bar bushings & end links",
    lede: "Clunk over small bumps is often end links, not the rack.",
    factory: "Bushings not walked out. End-link joints tight, boots intact. No clunk over speed bumps.",
    requires: "No clunk at the bar. Links tight.",
    measure: "Push the bar. Watch the bushings. Shake each end link. Road: small bumps.",
    good: "Quiet, tight, bushings in the saddles.",
    fail: "Clunk, torn link, bushing walked out. Replace links/bushings. Cheap and it changes the feel.",
    steps: [
      "Hands on the bar and each link. Photograph torn boots.",
      "Confirm on the first small bump of the drive.",
    ],
  }),
  ch({
    id: "steering.springs",
    section: "5. Steering / driveline",
    title: "Spring perches / shackles / body mounts",
    lede: "Rear shackles, front perches, body mounts. Rust and collapsed mounts make it wander and squeak.",
    factory: "Perches intact, shackles not egg-shaped, body mounts not collapsed to metal-on-metal.",
    requires: "No cracked perch, no broken leaf shackle, mounts doing their job.",
    measure: "Flashlight on front spring perches and rear shackles. Push on the body vs frame at a mount.",
    good: "Intact, not collapsed, not rusted through.",
    fail: "Rusted perch, egg-shaped shackle holes, cooked body mounts. Schedule. Do not ignore a perch crack.",
    steps: [
      "Front perches, rear shackles, a sample of body mounts.",
      "Photograph rust-through. Do not crawl under a scissor jack.",
    ],
  }),
  ch({
    id: "steering.shocks",
    section: "5. Steering / driveline",
    title: "Shock / strut leaks",
    lede: "Wet shock is a used-up shock. Cupped tires often start here.",
    factory: "Dry body, not dripping. Mounts intact. A light dusty film can be old; a wet streak is a fail.",
    requires: "No active leak. No broken mount.",
    measure: "Wipe the shock body. Look at the shaft. Bounce a corner — it should settle, not keep bouncing.",
    good: "Dry, controlled bounce.",
    fail: "Wet streak, broken mount, bounce that will not die, cupping. Replace as a pair on the axle.",
    steps: [
      "Look at all four. Photograph wet bodies.",
      "Bounce test. Pair with cupping on the tire line.",
    ],
  }),
  ch({
    id: "steering.rack",
    section: "5. Steering / driveline",
    title: "Rack boots / PSF high-pressure hose",
    lede: "Torn rack boot dumps grease and then the rack. The high-pressure PSF hose is a common leak on this chassis. Recheck PSF HOT after the drive.",
    factory: "Boots intact, dry. High-pressure hose dry. PSF in the HOT range after the drive, not burnt.",
    requires: "No torn boot, no wet hose, PSF not black.",
    measure: "Look at both rack boots. Follow the high-pressure hose from pump to rack. After the drive, read PSF HOT.",
    good: "Dry boots, dry hose, HOT PSF in range.",
    fail: "Torn boot, wet hose, groan at lock, burnt PSF. Replace hose/rack as required. Do not keep topping.",
    steps: [
      "Boots and hose, flashlight. Photograph wetness.",
      "After the drive, PSF HOT reading. Full-lock groan is a clue.",
    ],
  }),
  ch({
    id: "steering.shafts",
    section: "5. Steering / driveline",
    title: "Front & rear drive shafts / U-joints / slip yoke (4WD)",
    lede: "Vibration 45–70 that is not tires is often a U-joint or shaft. 4WD has a front shaft too.",
    factory: "U-joints have no perceptible play. Slip yoke not dry-seized. No clunk on take-up. Confirm any U-joint spec in the FSM.",
    requires: "No play, no rust-frozen joint, no missing strap bolts.",
    measure:
      "Under the truck, twist and pull each joint. Look at the rear slip yoke. On the drive, vibration that changes with speed but not with braking.",
    good: "Tight joints, no vibration 45–70 from the driveline.",
    fail: "Play, rusted joint, missing bolts, vibration. Replace joints/shaft. Do not ignore a clicking U-joint.",
    steps: [
      "Stands or lift. Hands on each joint. Photograph rust/play.",
      "4WD: front shaft too. Pair with the vibration road-test line.",
    ],
  }),
  ch({
    id: "steering.seals",
    section: "5. Steering / driveline",
    title: "CV / pinion / axle seals",
    lede: "Fresh gear oil or ATF at a seal is a leak. Dusty old film is a note. Pinion is the rear yoke.",
    factory: "Seals dry enough that you cannot wipe a fresh wet finger. Active dripping is a fail. Pair with the seep lines in Fluids.",
    requires: "No active drip at CV, pinion, or axle seals.",
    measure: "Flashlight on front CVs (4WD), rear axle seals, pinion. Wipe.",
    good: "Dry, or old dusty film only.",
    fail: "Fresh wet, flung oil on the back of a wheel. Schedule the seal. Check the matching fluid level.",
    steps: [
      "After a drive, look at CVs, axle ends, pinion.",
      "Photograph wetness. Fill the matching box on Fluids if it is a seep.",
    ],
  }),
  ch({
    id: "steering.mounts",
    section: "5. Steering / driveline",
    title: "Engine and transmission mounts",
    lede: "A cooked mount lets the VK56 bang on take-off and tears other things. Look, then have a helper load Drive and Reverse against the brake.",
    factory: "Rubber not split through, not collapsed onto the limiter. No metal-on-metal clunk on take-up.",
    requires: "Intact mounts, no bang in Drive or Reverse.",
    measure: "Visual on engine and trans mounts. Helper: brake on, idle, D then R — watch the engine rock.",
    good: "Controlled rock, rubber intact.",
    fail: "Split, collapsed, bang. Replace. Do not leave a trans mount until it shears the exhaust or the cooler lines.",
    steps: [
      "Visual, flashlight. Photograph cracked rubber.",
      "Load D and R against the brake. Watch the rock.",
    ],
  }),
  ch({
    id: "underbody.oilPan",
    section: "6. Underbody",
    title: "Oil pan and drain plug",
    lede: "Pan rail, drain plug, crush washer. Common seep at the pan and at the oil-cooler adapter above it.",
    factory: "New crush washer every drain. Plug torque from FSM SM5E-1T60U1 — do not guess. No active drip.",
    requires: "Plug present, not rounded, not weeping a stream. Pan not caved.",
    measure: "After a drive, flashlight on the pan rail and plug. Wipe.",
    good: "Dry enough, washer recently replaced if you just serviced it.",
    fail: "Streamer from the plug, stripped plug, cracked pan. Fix before the next drive.",
    steps: [
      "Look at the pan and plug. Photograph drips.",
      "If you drain: new washer, correct torque from the FSM, recheck after the drive.",
    ],
  }),
  ch({
    id: "underbody.transPan",
    section: "6. Underbody",
    title: "Transmission pan and cooler fittings",
    lede: "RE5R05A pan gasket and the two cooler lines. If you have never seen the inside at 270k, drop the pan once: new gasket, new filter, clean the magnet.",
    factory:
      "Fine grey film on the magnet is normal. Chunks and clutch flake are not. Pan drain ~4–6 qt, not a full 11¼. Matic J/S only. Do not high-pressure power-flush an unknown 270k unit.",
    requires: "No active drip at the pan or cooler fittings. Magnet/photo if you drop it.",
    measure: "Flashlight on the pan rail and cooler fittings after a drive. If you drop it, photograph the magnet.",
    good: "Dry rail, dry fittings, grey film only.",
    fail: "Drip, wet cooler fittings (SMOD path), chunks on the magnet. Do not keep driving hard.",
    steps: [
      "Look at the pan and cooler fittings. Photograph wetness.",
      "If history unknown at 270k: drop pan, photo the magnet, new filter/gasket, Matic J/S back, HOT level.",
    ],
  }),
  ch({
    id: "underbody.fuel",
    section: "6. Underbody",
    title: "Fuel tank, straps, lines, EVAP area",
    lede: "Smell, wetness, rusted straps, EVAP hoses dry-rotted at the tank.",
    factory: "No leak. Straps intact. Lines not rusted through. EVAP hoses not cracked. Any fuel wetness is a fail — do not drive it.",
    requires: "Dry tank and lines, straps not broken.",
    measure: "Flashlight, nose. Look at straps, the tank top/sides, metal lines, EVAP can and hoses.",
    good: "Dry, straps sound, no fuel smell.",
    fail: "Fuel smell/wet, broken strap, rusted line. Stop. Repair before you spark it.",
    steps: [
      "After a drive (heat helps). Look and sniff.",
      "Photograph rusted straps or wetness. Do not probe a wet tank with a trouble light that can spark.",
    ],
  }),
  ch({
    id: "underbody.exhaust",
    section: "6. Underbody",
    title: "Exhaust hangers, cats, muffler, leaks",
    lede: "Pair with the manifold tick. From the flanges back: hangers, cats, muffler, tips.",
    factory: "No blow at flanges. Hangers intact. Cats not rattling internally. Muffler not blown out. Manifold soot is the engine-bay line.",
    requires: "Quiet after warmup aside from a known manifold tick. Hangers holding.",
    measure: "Cold-ish after a short wait. Look at each flange for soot. Push hangers. Listen for cat rattle.",
    good: "Dry flanges, hangers intact, no blow.",
    fail: "Soot blow, broken hanger, rattling cat, hole in the muffler. Schedule. Exhaust in the cabin is a do-not-drive.",
    steps: [
      "Flanges, hangers, cats, muffler. Photograph soot.",
      "If cabin smell, fail the road test and do not keep driving it.",
    ],
  }),
  ch({
    id: "underbody.frame",
    section: "6. Underbody",
    title: "Frame rust, spare-tire carrier, running-board mounts",
    lede: "Frame, spare carrier under the rear, running-board / step mounts. Scale is one thing. Holes are another.",
    factory: "No rust-through at the frame, carrier, or step mounts. Spare carrier operates. Confirm any weld repair is structural, not a band-aid.",
    requires: "Solid frame in the usual rust belts (rear, steps, carrier). Spare can come down.",
    measure: "Ice pick or screwdriver — tap, do not spear blindly. Look at the spare carrier bolts and the step mounts.",
    good: "Surface scale OK at this age. No holes, carrier works.",
    fail: "Holes, crumbly frame, seized carrier, step hanging off. Schedule. A spare you cannot drop is a fail on that line.",
    steps: [
      "Walk the frame rails, steps, spare carrier.",
      "Try the carrier. Photograph rust-through.",
    ],
  }),
  ch({
    id: "underbody.lines",
    section: "6. Underbody",
    title: "Brake and fuel line rust",
    lede: "Hard lines along the frame. Surface rust is a note. Flake-to-hole is a fail.",
    factory: "Lines not rusted through. Clamps present. Any brake-line wetness is a do-not-drive.",
    requires: "Solid lines, no wetness.",
    measure: "Flashlight along the frame. Gently wipe. Look at bends and clamps.",
    good: "Surface rust only, dry, clamps on.",
    fail: "Flaking to holes, wet brake line, wet fuel line. Brake line: do not drive. Fuel line: do not drive.",
    steps: [
      "Follow brake and fuel lines. Photograph scabs.",
      "If wet, stop. This is not a “next visit” item.",
    ],
  }),
  ch({
    id: "cabin.airbag",
    section: "7. Cabin & safety",
    title: "Airbag lamp proves out and goes off",
    lede: "Key ON: lamp ON for prove-out, then OFF. A lamp that stays on is a stored SRS fault — not a pass.",
    factory: "Prove-out then off. Do not probe SRS with a test light. Do not clear codes to hide a lamp.",
    requires: "Lamp on, then off. Stays off. A stay-on or intermittent lamp is a hard gate — Pass is blocked.",
    measure: "Key ON, watch the cluster. If it stays on, scan SRS (not just powertrain).",
    good: "Prove-out then off.",
    fail: "Stays on, never comes on, or flickers. Diagnose. Do not call Pass with an airbag lamp.",
    steps: [
      "Key ON. Watch the airbag lamp.",
      "If it stays on, scan and write. Do not disconnect the battery to “reset” it for the report.",
    ],
  }),
  ch({
    id: "cabin.seatbelts",
    section: "7. Cabin & safety",
    title: "Seatbelts latch and retract — all rows",
    lede: "All three rows on an Armada. Latch, unlatch, retract. Torn webbing is a fail.",
    factory: "Every belt latches, unlatches, and retracts. No cut webbing. No missing tongues. Child-seat anchors present if equipped.",
    requires: "All rows checked, not just the fronts.",
    measure: "Pull each belt to the latch. Click. Jerk. Release. Let it retract. Look at the webbing.",
    good: "All latch and retract. Webbing intact.",
    fail: "Won’t latch, won’t retract, cut webbing, missing buckle. Replace. Do not knot a belt.",
    steps: [
      "Front, middle, third row. Both sides.",
      "Photograph damaged webbing. Write which seat failed.",
    ],
  }),
  ch({
    id: "cabin.latches",
    section: "7. Cabin & safety",
    title: "Doors / rear hatch / rear glass latch",
    lede: "Every door, the hatch, and the rear glass. A hatch that pops on the highway is a do-not-drive.",
    factory: "Each latch catches on the first slam, secondary catch works, interior and exterior handles work, child locks work if equipped.",
    requires: "All portals latch. Rear glass latches.",
    measure: "Open/close each door, hatch, rear glass. Try inside and outside handles. Confirm it stays shut when you pull.",
    good: "All latch and stay.",
    fail: "Won’t catch, pops open, handle dead, rear glass unlatched. Repair before you drive it.",
    steps: [
      "Walk around. Every door, hatch, glass.",
      "Photograph a failed latch. Do not tape a hatch shut and pass it.",
    ],
  }),
  ch({
    id: "cabin.horn",
    section: "7. Cabin & safety",
    title: "Horn",
    lede: "It has to work. Center of the wheel, a real honk.",
    factory: "Horn sounds from the pad. Both notes if dual. No delay.",
    requires: "Sounds when pressed.",
    measure: "Key ON or ACC as this truck needs. Press the pad.",
    good: "Loud, immediate.",
    fail: "Dead, faint, only one note if dual. Clock-spring / horn / fuse — fix it. A dead horn is a fail on this safety sheet.",
    steps: [
      "Key ON or ACC as this truck needs. Press the pad in the center of the wheel.",
      "Listen for a real honk, both notes if dual. If dead, check the horn fuse, then the clock-spring / switch.",
    ],
  }),
  ch({
    id: "cabin.lights",
    section: "7. Cabin & safety",
    title: "Lamps — headlights through hazards",
    lede: "Headlights, high beams, fogs, tails, brake, reverse, plate, hazards. Second person helps on brake and reverse.",
    factory: "Every bulb works. Aim not in other people’s eyes. Brake lights on both sides plus the high mount. Hazards work with key off.",
    requires: "Walk-around with a helper on brake/reverse/turn.",
    measure:
      "Key ON, engine still off for the first pass. Headlights low and high, fogs, tails, plate, hazards. Helper: brake, reverse, turns.",
    good: "Every lamp works.",
    fail: "Any dark bulb, cracked lens leaking water, brake light out. Replace before night driving. A dark brake lamp is a fail.",
    steps: [
      "Key ON. Walk around. Helper on brake and reverse.",
      "Hazards with key off. Photograph a dark lamp.",
    ],
  }),
  ch({
    id: "cabin.wipers",
    section: "7. Cabin & safety",
    title: "Wipers / washers front and rear",
    lede: "Front pair and the rear hatch. Rubber not torn. Washers wet the glass.",
    factory: "Wipe the glass clean, park at the bottom, rear works, washers spray. Replace torn rubber — do not flip a blade and pass it.",
    requires: "Front and rear wipe. Washers spray.",
    measure: "Key ON. Lift each blade, look at the rubber edge. Run front and rear. Spray washers.",
    good: "Clean wipe, rubber intact, both washers spray.",
    fail: "Torn rubber, chatter, dead rear, no spray. Replace blades / fix washer. Do not road-test rain-blind.",
    steps: [
      "Lift blades. Run front and rear. Spray.",
      "Replace torn rubber now if you have blades.",
    ],
  }),
  ch({
    id: "cabin.hvac",
    section: "7. Cabin & safety",
    title: "Defroster and HVAC blower",
    lede: "Defroster has to clear the glass. Blower on all speeds. A dead defroster is a fail in this climate.",
    factory: "Defrost blows on the windshield. Blower all speeds. Heat eventually with a warm engine. A/C optional for this safety line — defrost is not.",
    requires: "Defrost works. Blower not dead.",
    measure: "Key ON, engine can be running. Defrost mode, blower high, hand at the windshield ducts. Click through speeds.",
    good: "Air on the glass, all speeds.",
    fail: "No defrost, one speed only, burning smell. Repair. Do not pass a truck that cannot clear the windshield.",
    steps: [
      "Defrost + high blower. Feel the glass ducts.",
      "Click speeds. Note a burning smell as a fail.",
    ],
  }),
  ch({
    id: "cabin.glass",
    section: "7. Cabin & safety",
    title: "Mirrors / glass cracks",
    lede: "Driver’s view. A crack in the wiper sweep is a fail. Both outside mirrors present and usable.",
    factory: "No cracked windshield in the driver’s view. Mirrors present, glass not shattered. Rear glass latches (separate line) and is not a spiderweb.",
    requires: "Driver can see. No illegal crack in the sweep.",
    measure: "Stand outside and in the seat. Look at the windshield sweep, both mirrors, rear glass.",
    good: "Clear view, mirrors intact.",
    fail: "Crack in the sweep, missing mirror, shattered rear. Schedule glass. Do not drive a sweep crack as a pass.",
    steps: [
      "Sit in the seat. Look through the sweep.",
      "Walk the mirrors and rear glass. Photograph cracks.",
    ],
  }),
  ch({
    id: "cabin.jack",
    section: "7. Cabin & safety",
    title: "Jack, lug wrench, spare present and usable",
    lede: "Spare inflated, jack and lug wrench present, carrier works. A spare you cannot get down is not a spare.",
    factory:
      "Spare at the door-sticker pressure, legal tread, not 12 years old. Jack and wrench present. Carrier operates. Do not set the truck on this jack and crawl under it — it is for a roadside wheel change on level ground, then stands if you crawl.",
    requires: "Spare present and inflated. Jack and wrench present. Carrier works.",
    measure: "Find the jack/wrench. Drop or inspect the spare. Gauge it. DOT date on the spare.",
    good: "All present, spare holds air, carrier works.",
    fail: "Missing jack, missing wrench, flat spare, seized carrier. Fix it. You will need it on this truck.",
    steps: [
      "Locate jack and wrench. Inspect the spare and carrier.",
      "Gauge the spare. Write age on the tire-age line too.",
    ],
  }),
  ch({
    id: "cabin.recalls",
    section: "7. Cabin & safety",
    title: "Nissan campaigns",
    lede: "This visit, this VIN. Live NHTSA lookup of Nissan safety campaigns. The paper form keeps the dated stamp.",
    factory:
      "Open safety campaigns get done or written. Airbag, fuel, IPDM, and equipment campaigns on this chassis are not optional notes. NHTSA is the public Nissan campaign filing.",
    requires:
      "17-character VIN in the header. Tap Check Nissan campaigns. The form must read: Checked Nissan campaign list on [date] for VIN [vin].",
    measure:
      "VIN from the dash or door sticker. The app decodes it and pulls the NHTSA campaign list for that year/make/model. VIN-specific “already repaired” status is dealer-only — list campaigns here, note still-open work in notes.",
    good: "Stamp on the form with this VIN and today’s visit date. Campaigns listed. Any still-open dealer work written in notes.",
    fail: "No VIN, no lookup, or a Pass with an unrepaired safety campaign you already know is open. Do not.",
    steps: [
      "Enter the 17-character VIN from the dash or door in the header.",
      "Tap Check Nissan campaigns. Wait for the NHTSA list.",
      "Confirm the stamp: Checked Nissan campaign list on [date] for VIN [vin].",
      "Read campaign numbers (fuel gauge, IPDM, A/C fan, lower links on this truck). Note any still open at a dealer.",
      "The PDF carries the stamp so the file is defensible later.",
    ],
  }),
  ch({
    id: "road.coldStart",
    section: "8. Road test",
    title: "Cold start — chain and manifold noise recorded",
    lede: "The road-test box is the confirmation that you actually logged the cold-start noises from the engine-bay lines.",
    factory: "Timing-cover rattle seconds and manifold tick/soot already written. Do not skip the cold start and then guess.",
    requires: "Those engine-bay lines filled. This box checked only after that.",
    measure: "Look back at timing cover and manifolds. Copy the result here as “recorded.”",
    good: "Recorded. Quiet or a known short rattle, manifolds noted.",
    fail: "Never listened cold. Ongoing rattle or tick+soot not written.",
    steps: [
      "Do the cold start first, before the drive.",
      "Check this box only after timing-cover and manifold lines have numbers/notes.",
    ],
  }),
  ch({
    id: "road.overheat",
    section: "8. Road test",
    title: "No overheat after 15 min mixed driving",
    lede: "Temp gauge settles at the normal middle mark and stays there. Climbing toward H in normal driving: stop.",
    factory: "Gauge in the middle, stable. Not toward H. Skip the drive if ATF is rejected or coolant is empty.",
    requires: "15 min mixed driving. Gauge stable Y/N.",
    measure: "Watch the gauge the whole drive. After 15 min it must be stable in the middle.",
    good: "Stable, middle. Gauge stable Y.",
    fail: "Climbing, bouncing, steam, smell. Stop. Cooling problem. Do not finish the loop to “see.”",
    steps: [
      "Mixed road, 15 minutes. Watch the gauge.",
      "Write stable Y/N. Stop if it climbs.",
    ],
  }),
  ch({
    id: "road.brakes",
    section: "8. Road test",
    title: "Brakes from 30 and from 60 — no pull, no pulse",
    lede: "Moderate stops, not panic stops. Straight, firm, no shake.",
    factory: "Straight, firm pedal, no shake. Pull, pulse (rotors), soft pedal that sinks, grinding: fail. Pair with pad/rotor measurements.",
    requires: "One stop from ~30 and one from ~60 in a safe place.",
    measure: "Hands light, brake straight. Feel pull and pulse in the pedal/wheel.",
    good: "Straight, firm, no pulse.",
    fail: "Pull, pulse, sink, grind. Measure rotors/pads. Do not keep doing 60s on a pulsing truck.",
    steps: [
      "Safe road. ~30 mph moderate stop. Then ~60.",
      "Log pull/pulse. Photograph nothing — write it, then recheck rotors.",
    ],
  }),
  ch({
    id: "road.vibration",
    section: "8. Road test",
    title: "No new vibration 45–70 mph",
    lede: "Shake that changes with speed = tires / balance / U-joint / shaft. Not a “road’s rough” shrug.",
    factory: "None at 45–70. If it shakes, isolate tires vs driveline (does it change in a turn, or only on throttle).",
    requires: "Cruise 45–70. No new shake.",
    measure: "Smooth road. 45, 55, 65. Note throttle on vs coast.",
    good: "No new vibration at 45–70 mph on a smooth road.",
    fail: "Shake. Check balance, inner tires, U-joints, shafts. Do not pass it as character.",
    steps: [
      "Cruise 45–70 on a smooth road.",
      "If it shakes, note speed and throttle. Inspect tires and shafts.",
    ],
  }),
  ch({
    id: "road.shifts",
    section: "8. Road test",
    title: "Shift quality matches Section 3",
    lede: "The road test is not a second opinion that undoes a failed 1–2. It confirms the table.",
    factory: "Matches the cold/hot table. Flare, missing 5th, TCC shudder, delay that grows hot: failing trans.",
    requires: "Section 3 filled. This box = the drive agreed.",
    measure: "Drive the same checks: take-up, 1–2, 2–3, 4–5, TCC, kickdown.",
    good: "Matches a clean table.",
    fail: "Drive is worse than the table, or the table was already flare/shudder. Do not Pass.",
    steps: [
      "Fill Section 3 on the drive.",
      "Check this box only if the table and the seat-of-pants agree.",
    ],
  }),
  ch({
    id: "road.lamps",
    section: "8. Road test",
    title: "No new warning lamps",
    lede: "Nothing new after the drive. If a lamp comes on, stop and scan. Do not clear codes until you write them.",
    factory: "No new dash lamps. Stop and scan. Write stored/pending.",
    requires: "Cluster clean aside from known-old items already written.",
    measure: "Watch the cluster the whole drive and after shutdown/restart.",
    good: "No new lamps.",
    fail: "New CEL, AT, ABS, oil, temp. Stop. Scan. Do not Pass.",
    steps: [
      "Watch the cluster. If a lamp comes on, stop and scan.",
      "Write codes on the scan line. Do not clear first.",
    ],
  }),
  ch({
    id: "baseline.sparkPlugs",
    section: "270k due",
    title: "Spark plugs (105k iridium — cycle 2 or 3)",
    lede: "VK56DE iridium plugs are a 105,000-mile item. At 270k you are on cycle 2 (210k) or heading into cycle 3 (315k). Unknown last change is a Fail, not a note.",
    factory:
      "Nissan iridium spark plugs, 105,000-mile interval on this 5.6. Coil-on-plug, eight plugs. Confirm plug type in FSM SM5E-1T60U1 before you buy. Do not gap a worn iridium tip as a “fix.”",
    requires:
      "Last replaced miles written, or Unknown. Cycle 2 or 3 marked. Pass or Fail. Pass only if last change is within 105k of current miles and you can prove it.",
    measure:
      "Current miles minus last plug miles. If last is unknown, treat as overdue. Pull one coil only if you are actually inspecting — boot oil is a valve-cover / tube-seal issue, not a plug-gap issue.",
    good: "Last change within 105k, iridium still in spec, boots dry. Pass.",
    fail: "Unknown last change at 270k. Last change ≥105k ago. Oil in the tubes. Misfire. Cycle 1 claimed at 270k is not honest.",
    steps: [
      "Write current miles and last plug miles. If you cannot prove last change, mark Unknown and Fail.",
      "270 ÷ 105 ≈ 2.6 — you are on cycle 2 or 3, not cycle 1.",
      "If replacing: one bank at a time, anti-seize only if the plug spec says so, torque to FSM, dielectric on the boot.",
      "Grade Pass or Fail. A note is not a grade.",
    ],
  }),
  ch({
    id: "baseline.coolantService",
    section: "270k due",
    title: "Coolant service + cap + thermostat + water-pump weep",
    lede: "Glance at the reservoir is not a coolant service. At 270k, unknown history means drain, cap, thermostat behavior, and the water-pump weep hole.",
    factory:
      "50/50 Nissan Long Life (HOAT) and distilled water. System about 14.4 L / 3¾ gal. Service about 60,000 miles / 5 years if history is unknown. Never tap water. Never Dex-Cool mixed in. Radiator cap holds system pressure — a weak cap is overheat. Thermostat must let the gauge reach the normal middle and stay there. Water-pump weep hole at the 6 o’clock of the pump: wet = the pump is done.",
    requires:
      "Last service miles/year or unknown. Cap Pass/Fail. Thermostat Pass/Fail (gauge to middle, not stuck cold or jumping to H). Weep dry/wet. Overall Pass or Fail.",
    measure:
      "Engine COLD for cap and weep. After the drive: gauge must sit at the normal middle. Weep hole: look at the pump body below the pulley for dried coolant or a wet streak. Do not open the radiator cap hot.",
    good: "Service in the last 60k / 5 years, cap holds, gauge stable at middle, weep dry.",
    fail: "Unknown or overdue service. Weak/unseated cap. Gauge never warms or climbs to H. Wet weep hole. Oily coolant is SMOD — stop.",
    steps: [
      "Cold: reservoir level, color, freeze point. Cap seated. Photograph the weep hole.",
      "Drive: gauge to the middle and stays. Stuck closed overheats. Stuck open never warms.",
      "If history unknown at 270k: drain cold, flush distilled, new cap if weak, refill 50/50 Nissan LL.",
      "Wet weep: replace the pump (and usually the thermostat while you are there). Grade Pass or Fail.",
    ],
  }),
  ch({
    id: "baseline.brakeFluid",
    section: "270k due",
    title: "Brake fluid (DOT 3, moisture)",
    lede: "DOT 3 is hygroscopic. At 270k, “it still looks ok” is not a 24-month flush. Grade it.",
    factory:
      "DOT 3 from a sealed bottle. Flush every 24 months regardless of miles. Never DOT 5 silicone. Never an old open bottle. Reservoir never dry during a bleed. Color should be light honey / pale yellow. High moisture fails the fluid even if the pedal is firm today.",
    requires: "Last flush date/miles or unknown. Color and moisture already on the fluids row. Pass or Fail on this 270k line.",
    measure:
      "Wipe the cap. Read MIN/MAX. Color: clear-amber vs dark. Moisture chip from the fluids row. If last flush is unknown or >24 months, Fail and flush.",
    good: "Flushed within 24 months, light honey, dry, cap sealed, pedal later firm.",
    fail: "Unknown last flush at 270k. Dark brown/black. High moisture. Below MIN (pads or leak). Wet master — do not drive.",
    steps: [
      "Write last flush. Unknown at 270k is a Fail.",
      "Color and moisture. Dark or high moisture: DOT 3 bleed, one corner at a time, reservoir never dry — or a shop.",
      "Grade Pass or Fail. Do not hide overdue fluid in notes.",
    ],
  }),
  ch({
    id: "baseline.diffFluid",
    section: "270k due",
    title: "Diff and transfer-case fluid",
    lede: "Seep look is not a fluid change. 30k item. Fill-plug level, color, glitter. 2WD is rear only.",
    factory:
      "Rear and front (4WD): API GL-5 80W-90 (synthetic 75W-90 ok for heat). Front about 1.6 L / 3⅜ pt. Rear about 1.8 L / 3¾ pt — confirm in FSM. Transfer (4WD): Nissan Matic D, about 3.0 L / 3⅛ qt. Change every 30,000 miles. Fill to the fill-plug hole, truck level.",
    requires:
      "Each fill plug Pass/Fail: rear always; front and transfer on 4WD. Overall Pass or Fail. Level at the hole, not milky, not glitter-heavy, not burnt tar.",
    measure:
      "Park level after a drive. Upper fill plug out — not the drain. Finger at the hole. Oil should wet the finger. Smell and color. Photograph seepage vs the fill.",
    good: "Level at the hole, gear oil looks like gear oil, transfer is Matic D not milky. Last change within 30k or you just serviced it.",
    fail: "Low, milky, glitter, burnt, unknown last change at 270k (nine 30k intervals overdue). Seep-only with no fill-plug check is a Fail on this line.",
    steps: [
      "2WD: rear only. 4WD: transfer, front, rear.",
      "Fill plug out. Finger wet at the hole. Color, smell, glitter.",
      "If unknown at 270k: drain/fill to spec. Grade each plug, then the line Pass or Fail.",
    ],
  }),
  ch({
    id: "baseline.seepage",
    section: "270k due",
    title: "Valve-cover / timing-cover / oil-pan seepage grade",
    lede: "VK56 seeps. Grade each: dry, film, wet, drip. Wet or drip is a Fail — not “watch it.”",
    factory:
      "No published drip rate. Dusty film on an old gasket at 270k is common. Fresh wet that wets a finger is a leak. Active drip is not a watch item. Valve-cover gaskets, front cover, oil-cooler O-ring at the block, pan rail are the usual sources.",
    requires: "A grade on valve covers, timing cover, and oil pan. Overall Pass or Fail. Photograph wetness.",
    measure:
      "After a drive, engine off a few minutes. Flashlight. Wipe a finger: dry / dusty film / fresh wet / drip on the ground. Timing cover is the front of the engine. Pan is underneath — stands on the frame.",
    good: "Dry, or dusty film that does not wet the finger. Pass with the grades written.",
    fail: "Wet or drip at covers, timing cover, or pan. Oil-cooler O-ring wet. Puddle on the ground. Do not call that a note.",
    steps: [
      "Grade valve covers, timing cover, pan: dry / film / wet / drip.",
      "Photograph anything wetter than film.",
      "Overall Pass only if nothing is wet or dripping. Grade it.",
    ],
  }),
  ch({
    id: "baseline.manifoldBolts",
    section: "270k due",
    title: "Exhaust manifold / heat-shield bolts",
    lede: "VK56 classic: heat-shield bolts back out, shields rattle, manifolds crack. This line is the bolts and shields, not just the cold tick.",
    factory:
      "Heat shields stay bolted. Missing or loose bolts are a fail. A sooty stripe at the manifold-to-head flange is a crack or gasket — schedule. Confirm fastener torque in FSM SM5E-1T60U1. Do not “snug it” with the engine hot.",
    requires: "Both banks: shields present, bolts present and tight. Pass or Fail. Soot Y/N already on the cold-start manifold line.",
    measure:
      "Engine off, after warmup cool enough to touch the shields, not the manifold. Wiggle each shield. Count bolts. Flashlight at the flange for soot. Cold tick plus soot is the other line — this line is hardware.",
    good: "Shields tight, bolts present, no rattle, no missing hardware.",
    fail: "Loose or missing heat-shield bolts, rattling shield, broken stud. Schedule hardware (and manifolds if soot + tick).",
    steps: [
      "Both banks. Wiggle the shields. Missing bolt = Fail.",
      "Photograph gaps or soot at the flange.",
      "Grade Pass or Fail. Do not leave missing bolts as a note.",
    ],
  }),
  ch({
    id: "baseline.ucaJoints",
    section: "270k due",
    title: "Upper control arms / ball joints",
    lede: "Inner pad taper and inner tire wear on this chassis are UCAs until proven otherwise. Grade the joints, not the alignment shop later.",
    factory:
      "No rock at the upper or lower ball joint. UCA bushings not collapsed. Inner-shoulder tire wear or inner pad taper means alignment after the arms, not just new tires. Replace, then align. Confirm any torque in the FSM.",
    requires: "12-and-6 rock Pass/Fail. Inner taper Y/N written. Overall Pass or Fail.",
    measure:
      "Stands. 12 and 6 on each front tire. Pry the joint to separate hub play from ball-joint play. Look at UCA bushings. Pair with the pad mm and tire-wear lines.",
    good: "Tight joints, decent bushings, even inner/outer pads and tires.",
    fail: "Clunk, torn boot, collapsed UCA bushing, inner pad taper, inner tire wear. Schedule UCAs/joints and alignment. Do not just buy tires.",
    steps: [
      "12-and-6. Pry the joint. Photograph torn boots / collapsed bushings.",
      "Mark inner taper Y/N from the pad and tire lines.",
      "Grade Pass or Fail. Inner taper with “watch the arms” in notes is a Fail.",
    ],
  }),
  ch({
    id: "baseline.airShocks",
    section: "270k due",
    title: "Rear load-leveling / air shocks",
    lede: "Some 2005 Armadas have rear load-leveling. If not equipped, Pass. If equipped, leaks and sag are a Fail — not a ride-quality note.",
    factory:
      "If equipped: rear air/load-leveling shocks hold height, dry, compressor not short-cycling. A wet air shock is used up. Pair of the axle. If not equipped, conventional shocks still get the leak look on the shock line — this line is N/A Pass.",
    requires: "Equipped Y/N. If N: Pass. If Y: height even, dry, compressor quiet. Pass or Fail.",
    measure:
      "Look at the rear shocks. Air lines and a compressor/dryer mean equipped. Park on level ground: rear sit even, not one-side sag. Wet streak on the air shock body is a leak. Bounce: it should settle.",
    good: "Not equipped (Pass), or equipped, dry, level, compressor not running constantly.",
    fail: "Equipped and sagging, wet, or compressor short-cycling. Replace as a pair. Do not keep adding air to a leak.",
    steps: [
      "Decide equipped Y/N. Not equipped: Pass this line.",
      "If equipped: height, wetness, compressor behavior. Photograph sag or wetness.",
      "Grade Pass or Fail.",
    ],
  }),
  ch({
    id: "result.smodPlan",
    section: "9. Result",
    title: "SMOD prevention — 30k / 270k",
    lede: "Detection is pink, milky, or sweet ATF. Prevention is an external stacked-plate cooler and a new radiator before that happens. At 270k, red ATF today is not a maintenance plan.",
    factory:
      "The 2005 Armada radiator has a small ATF cooler in the tank. That chamber cracks; coolant and ATF mix and kill the RE5R05A (SMOD). Nissan does not publish a “replace radiator to prevent SMOD” mile. This shop’s 30k powertrain action is: bypass the in-radiator cooler to an external stacked-plate cooler, cap the radiator ATF ports, and replace the radiator if it is original, unknown, or the tanks are 10+ years old. Highest-value job on a 2005 that still shifts.",
    requires:
      "Radiator last replacement: original/unknown or year. Cooler fittings photo — required on 30k / 270k, and whenever fittings are wet. Bypass already done Y/N on the cooler-lines row. Write the plan even if ATF is still red.",
    measure:
      "Year or YYYY-MM on the radiator if it was replaced; otherwise original/unknown. Photograph the two small ATF fittings at the radiator tank (wet or dry). Confirm whether an external cooler is actually installed and the radiator ports are capped.",
    good: "External cooler installed, radiator replaced with a date on the form, fittings photo on file, ATF still red/amber. Plan is closed.",
    fail: "Original or unknown radiator, or in-radiator cooler still in service, at 30k / 270k. Wet fittings with no photo. Calling Pass because “it isn’t milky today.”",
    steps: [
      "This is the 30k / 270k result action — not the oil-change glance.",
      "Write radiator last: original/unknown, or the replacement year.",
      "Photograph the ATF cooler fittings at the radiator. Required, even if dry.",
      "If bypass is not done: schedule external stacked-plate cooler + radiator replacement. Cap the old ports.",
      "If ATF is already pink/milky/sweet: stop. Prevention is too late — see ATF reject. Do not bypass-and-drive.",
      "Stamp the form: not milky today is not a maintenance plan.",
    ],
  }),
  ch({
    id: "result.overall",
    section: "9. Result",
    title: "Overall result & sign-off",
    lede: "Pass means normal for mileage. Do not drive means park it. Pink/milky/sweet ATF cannot be a Pass. Neither can a pad at 1.0 mm, a rotor at min, a collapsed rest voltage, an ABS or airbag lamp that stays on, a pedal below spec, or an ongoing timing-cover rattle with low oil pressure.",
    factory:
      "Oil change 3,500–5,000 miles or 6 months. 15k: measured brakes, cabin filter, front end, battery, manifold soot. 30k: ATF drain/fill (pan/filter if due), diffs + transfer, brake fluid if 24 months, air filter, hoses, alignment if inner wear. Confirm fasteners in FSM SM5E-1T60U1. Hard gates auto-block Pass: SMOD; pad ≤ 1.0 mm; rotor ≤ min; rest V < 12.2; active ABS/airbag lamp; pedal < 3.5 in; ongoing timing rattle plus low oil pressure.",
    requires:
      "Date, miles, inspector on the header. Every inspected row has a status: Pass / Monitor / Needs attention / Repair ASAP / N/A. Overall circled. Fail items written. Next service miles written. Name and date. Score prints at the top of the form.",
    measure: "Read the fail items out loud. If a hard gate is open, overall is Do not drive. Pass and Pass with notes are blocked.",
    good: "No hard gates. Pass, or Pass with notes for watch items (dusty seeps, short cold rattle).",
    fail: "Do not drive: SMOD, pad at 1.0 mm, rotor at min, rest V collapsed, ABS/airbag lamp staying on, pedal below spec, ongoing timing rattle plus low oil pressure, brake leak, fuel leak, overheat. Schedule repairs: everything else that is not safe-to-ignore.",
    steps: [
      "Header complete. Fail items listed in plain language.",
      "If ATF is pink/milky/sweet: Do not drive. Never Pass.",
      "If a pad is ≤ 1.0 mm, a rotor is at min, rest V is collapsed, an ABS or airbag lamp is staying on, the pedal is below spec, or an ongoing timing rattle sits with low oil pressure: Do not drive. Never Pass.",
      "Write next oil / 15k / 30k miles. Sign name and date.",
    ],
  }),
];

const CHAPTER_ALIASES: Record<string, string> = {
  caliper: "brakes.hoses",
  calipers: "brakes.hoses",
};

export function findChapter(id: string): GuideChapter | undefined {
  const mapped = CHAPTER_ALIASES[id] ?? id;
  return GUIDE_CHAPTERS.find((c) => c.id === mapped);
}

export function chapterSearchText(ch: GuideChapter): string {
  return [
    ch.id,
    ch.section,
    ch.title,
    ch.lede,
    ch.factory,
    ch.requires,
    ch.measure,
    ch.good,
    ch.fail,
    ch.searchExtra ?? "",
    ...ch.steps,
  ]
    .join(" ")
    .toLowerCase();
}
