/** First sentence of each beginner-card why/what. Tiny index so Home never loads plain.ts. */
const MEANING: Record<string, string> = {
  "fluids.oilLevel": "This engine is hard on timing chains if it runs low.",
  "fluids.oilLeak": "A slow seep is common at 270k.",
  "fluids.coolant": "Oil film or a red tint in here can mean coolant is mixing with oil or ATF (automatic transmission fluid).",
  "fluids.atf": "On this truck the cooler lives inside the radiator.",
  "fluids.psf": "The high-pressure hose on this chassis likes to leak.",
  "fluids.brake": "A slow drop follows pad wear.",
  "fluids.washer": "Empty washers are a ticket and a safety problem, not an engine problem.",
  "fluids.transferSeep": "A seep here is gear oil, not engine oil.",
  "fluids.frontDiffSeep": "Gear oil on the ground is this, not engine oil.",
  "fluids.rearDiffSeep": "Same as the front: gear oil leak vs dusty stain.",
  "engine.timingCover": "VK56 chains rattle when oil is slow to get there.",
  "engine.manifolds": "VK56 manifold and heat-shield bolts like to break.",
  "engine.idle": "A rough idle or a CEL that stays on means a sensor, vacuum leak, or misfire.",
  "engine.belt": "A cracked belt can leave you with no charge and a hot engine.",
  "engine.radiator": "If that cooler fails inside, coolant and transmission fluid mix.",
  "engine.atfLines": "If the radiator fails internally, coolant and transmission fluid can mix.",
  "engine.airFilter": "A packed filter starves a 5.6 and throws dust into the MAF sensor.",
  "engine.battery": "A weak battery on this truck makes lamps and the TCM act possessed.",
  "engine.grounds": "A rusty ground on an Armada makes random electrical ghosts — gauges, 4WD, TCM.",
  "engine.pcv": "A cracked PCV hose is a vacuum leak — rough idle, whistle, oil breath.",
  "engine.scan": "This gearbox wants a HOT ATF read near 149°F.",
  "trans.parkReverse": "The RE5R05A (this truck’s 5-speed) often warns you with a flare, bang, or miss before it fails.",
  "trans.reverseDrive": "The RE5R05A (this truck’s 5-speed) often warns you with a flare, bang, or miss before it fails.",
  "trans.up12": "The RE5R05A (this truck’s 5-speed) often warns you with a flare, bang, or miss before it fails.",
  "trans.up23": "The RE5R05A (this truck’s 5-speed) often warns you with a flare, bang, or miss before it fails.",
  "trans.up345": "The RE5R05A (this truck’s 5-speed) often warns you with a flare, bang, or miss before it fails.",
  "trans.tcc": "A shudder here is a classic RE5R05A complaint.",
  "trans.kickdown": "The RE5R05A (this truck’s 5-speed) often warns you with a flare, bang, or miss before it fails.",
  "trans.fourwd": "A bind on dry pavement is normal in 4HI if you turn sharp.",
  "trans.atfReject": "That mix is SMOD.",
  "brakes.pads": "Uneven inner vs outer on this truck often means a sticky caliper or a worn UCA (upper control arm) that lets the wheel lean.",
  "brakes.rotors": "A pulse in the pedal is often a rotor.",
  "brakes.hoses": "A wet caliper is a fail.",
  "brakes.master": "Seepage at the back of the master drips on the booster and then the carpet.",
  "brakes.pedalHeight": "A low pedal means worn pads, air, or a master that is bypassing.",
  "brakes.parking": "A parking brake that needs 10 clicks is stretched or seized.",
  "brakes.absLamps": "A lamp that stays on means you may not have anti-lock next time you panic-stop.",
  "brakes.tread": "Inner-shoulder wipe on this truck is often alignment or a tired UCA, not “I need new tires only.”",
  "brakes.tireAge": "Old rubber cracks even with tread.",
  "brakes.wear": "Inner wear + a pull is alignment or UCA play.",
  "brakes.pressures": "Low inner heat cooks a tire.",
  "brakes.lugTorque": "Too loose = wheel walks.",
  "brakes.bearings": "A growl that changes in a turn is a bearing, not a tire.",
  "brakes.alignment": "A pull plus inner pad taper is a UCA or inner-tie-rod story on this chassis.",
  "steering.steeringPlay": "Play here is the box, the column, or the joints you check next.",
  "steering.tieRods": "A loose tie rod is clunk + inner tire wear + a death wobble risk.",
  "steering.ballJoints": "Tired UCAs on this truck eat inner pads and ruin alignments.",
  "steering.sway": "A clunk over driveways is often these, not the transmission.",
  "steering.springs": "A collapsed perch or a rotten body mount changes alignment and pad wear.",
  "steering.shocks": "A wet shock plus inner tire cupping is a replace, not an alignment first.",
  "steering.rack": "A torn boot dumps grease and then play.",
  "steering.shafts": "A vibration 45–70 that you did not have last year is often a U-joint, not “tires.”",
  "steering.seals": "A wet seal is gear oil or grease leaving.",
  "steering.mounts": "A torn mount lets the engine jump and can look like a slam shift.",
  "underbody.oilPan": "A leaking pan rail or a reused crush washer drips the oil you just paid for.",
  "underbody.transPan": "Wet fittings from below are the same SMOD story.",
  "underbody.fuel": "A fuel smell or a wet line is a fire problem, not a “next oil change” problem.",
  "underbody.exhaust": "Broken hangers drag.",
  "underbody.frame": "Rust at running-board mounts and the spare carrier is how these trucks get dangerous, not just ugly.",
  "underbody.lines": "Rusty brake line is a blowout later.",
  "cabin.airbag": "A bag lamp that stays on means the bag may not fire — or may fire for no reason.",
  "cabin.seatbelts": "A belt that will not latch is not a “later” item.",
  "cabin.latches": "A hatch that pops on the highway is a wreck, not an annoyance.",
  "cabin.horn": "A dead horn is a safety fail and a ticket in some places.",
  "cabin.lights": "A dark brake light is how someone finds your bumper.",
  "cabin.wipers": "You cannot inspect what you cannot see in a Ventura County marine layer.",
  "cabin.hvac": "No defrost in a rain is a safety fail.",
  "cabin.glass": "A crack in the driver’s view is a ticket and a blow risk.",
  "cabin.jack": "A frozen spare carrier is a 2005 Armada classic.",
  "cabin.recalls": "Airbag and sensor campaigns on this era are real.",
  "road.coldStart": "Timing-cover rattle and manifold tick show up here, then hide when hot.",
  "road.overheat": "A climb past the middle on this truck is a radiator, cap, or fan story — and it can become SMOD if the tanks are original.",
  "road.brakes": "Pull and pulse show up at speed.",
  "road.vibration": "Tires, a U-joint, or a bent wheel.",
  "road.shifts": "A flare that only happens hot will show here, not in the driveway.",
  "road.lamps": "A lamp that appears hot is a real fault, not a prove-out.",
  "baseline.sparkPlugs": "The interval is 105k.",
  "baseline.coolantService": "Unknown coolant at 270k is rust and a popped tank waiting.",
  "baseline.brakeFluid": "Old DOT 3 eats internals and boils on a long grade.",
  "baseline.diffFluid": "At 270k “it isn’t dripping” is not a fluid change.",
  "baseline.seepage": "A drip is a leak.",
  "baseline.manifoldBolts": "A ticking heat shield is annoying.",
  "baseline.ucaJoints": "Play here is inner pad taper and a pull.",
  "baseline.airShocks": "A sagging rear with a compressor that never sleeps is a leak, not “it is old.”",
  "result.smodPlan": "At 270k, “not milky today” is not a maintenance plan.",
  "result.overall": "Pass is blocked if a hard gate is open: SMOD, pad at 1 mm, rotor at min, dead rest voltage, ABS/airbag lamp staying on, low pedal, ongoing timing rattle plus low oil.",
  "engine.overview": "A close-up of a fitting without this shot is hard to trust later.",
  "cabin.dash": "“I think the ABS went out” is not a photo.",
};

export function meaningFor(guideId: string, fallback: string): string {
  if (!guideId) return fallback;
  return MEANING[guideId] || fallback;
}
