export const DIAGRAM_KINDS = [
  "oil",
  "atf",
  "radiator",
  "coolant",
  "battery",
  "pads",
  "tire",
  "engine",
  "trans",
  "under",
  "cabin",
  "steering",
  "brake",
  "leak",
] as const;

export type DiagramKind = (typeof DIAGRAM_KINDS)[number];

export interface PlainExplain {
  id: string;
  diagram: DiagramKind;
  what: string;
  where: string;
  why: string;
  good: string;
  bad: string;
  next: string;
  tools: string;
  specPlain: string;
  looksGood: string;
  secondLook: string;
  stopShop: string;
}

function p(
  id: string,
  diagram: DiagramKind,
  fields: {
    what: string;
    where: string;
    why: string;
    good: string;
    bad: string;
    next: string;
    tools: string;
    specPlain: string;
    looksGood?: string;
    secondLook?: string;
    stopShop?: string;
  },
): PlainExplain {
  return {
    id,
    diagram,
    ...fields,
    looksGood: fields.looksGood ?? fields.good,
    secondLook: fields.secondLook ?? `Needs a second look: ${fields.bad}`,
    stopShop: fields.stopShop ?? fields.next,
  };
}

const SHIFT = (id: string, name: string, feel: string): PlainExplain =>
  p(id, "trans", {
    what: `This is one gear change in the automatic. You are feeling whether it happens cleanly.`,
    where: `Driver seat. Do this on a quiet road after the truck is warm. Cold and hot each get a mark.`,
    why: `The RE5R05A (this truck’s 5-speed) often warns you with a flare, bang, or miss before it fails. Catch it early.`,
    good: `${name} feels ${feel}. No bang, no long pause, no engine RPM flare.`,
    bad: `Delay, bang, flare, hunt, or a miss. Repeat once to be sure it was not your foot.`,
    next: `Pass if both cold and hot feel clean. Monitor a one-time odd shift. Shop if it repeats or bangs.`,
    tools: `Quiet road, a passenger to write, working brakes.`,
    specPlain: `No published “ms of delay.” Clean engagement is the spec. Bang or flare is not.`,
    looksGood: `Clean, one motion.`,
    secondLook: `One odd shift — try again warm.`,
    stopShop: `Repeated bang, flare, or miss — shop. Do not keep driving a harsh reverse engagement.`,
  });

export const PLAIN: PlainExplain[] = [
  p("fluids.oilLevel", "oil", {
    what: `Engine oil is the slippery film that keeps the 5.6 from grinding itself.`,
    where: `Under the hood, driver-side front. Long yellow or marked handle. Not the skinny trans stick.`,
    why: `This engine is hard on timing chains if it runs low. An oil-change visit records what you poured — not a dipstick after you dumped the pan.`,
    good: `Oil change: 5W-30 in, about 6.5 quarts, filter written, new crush washer. 15k: film between L and H, not milky.`,
    bad: `Below L, milky chocolate milk, fuel smell, or unknown oil dumped in.`,
    next: `Pass if the change is recorded or the stick is in range. Shop if it is milky. Add 5W-30 only if it is truly low on a 15k.`,
    tools: `Funnel, 5W-30, filter, crush washer, lint-free rag, drain pan.`,
    specPlain: `Genuine Nissan 5W-30. Capacity with filter is 6.2 L / 6½ qt. Change about every 3,500–5,000 miles at this age.`,
  }),
  p("fluids.oilLeak", "leak", {
    what: `This is a look for oil that has escaped the engine — wet spots, not just old dust.`,
    where: `Valve covers on top, oil-cooler adapter at the block, filter, pan, and the front timing cover. Also the ground where it sat.`,
    why: `A slow seep is common at 270k. A drip that empties the stick is how this engine eats a chain.`,
    good: `No fresh wet finger. No puddle. Old dusty stain can be a watch.`,
    bad: `Active drip, soaked timing cover, wet oil-cooler O-ring, or a puddle overnight.`,
    next: `Pass if dry or only dusty film. Monitor a stain. Shop for a drip. Photograph the wet spot.`,
    tools: `Flashlight, paper towel, camera.`,
    specPlain: `No allowed drip rate. Wet on a finger is a leak. Dusty film is a note.`,
  }),
  p("fluids.coolant", "coolant", {
    what: `Coolant is the mix that keeps the engine from boiling or freezing. You read the plastic overflow tank, not the radiator.`,
    where: `Front of the bay, next to the radiator. MIN and MAX are molded in the tank.`,
    why: `Oil film or a red tint in here can mean coolant is mixing with oil or ATF (automatic transmission fluid). That is an emergency on this Nissan.`,
    good: `Between MIN and MAX. Uniform color. No oil sheen. Cap seated. Engine cold.`,
    bad: `Empty, rusty mud, oil film, or strawberry/red tint.`,
    next: `Pass if the tank is in range and clean. Do not drive if it is empty or milky. Do not open the radiator cap hot.`,
    tools: `Flashlight, camera. Freeze-point tester if you have one.`,
    specPlain: `50/50 Nissan Long Life and distilled water. System about 14.4 L / 3¾ gal. Service about 60k miles / 5 years if history is unknown. Factory freeze around −34°F.`,
  }),
  p("fluids.atf", "atf", {
    what: `ATF is automatic transmission fluid — the oil the gearbox lives in.`,
    where: `Passenger-side firewall. Skinny stick with a small bolt through the handle. Engine must be idling.`,
    why: `On this truck the cooler lives inside the radiator. If they mix, you get SMOD — strawberry milkshake of death — and the transmission can die.`,
    good: `HOT range, engine idling. Transparent red or amber. Smells like ATF, not sweet.`,
    bad: `Pink, milky, strawberry, or sweet. That is coolant in the ATF.`,
    next: `Pass only if it is red/amber in the HOT range. Do not keep driving if it is milky or sweet. Shop the same day.`,
    tools: `Lint-free paper, 10 mm for the handle bolt, level pavement.`,
    specPlain: `Only Nissan Matic J (or Matic S). Read HOT marks after a drive, stick inserted reversed, about 149°F / 65°C. Never check with the engine off.`,
    looksGood: `Red/amber, HOT hashes, not sweet.`,
    secondLook: `Brown or burnt smell — schedule a drain/fill.`,
    stopShop: `Pink, milky, or sweet — park it. That is SMOD.`,
  }),
  p("fluids.psf", "coolant", {
    what: `Power steering fluid is what lets you turn the wheel without wrestling it.`,
    where: `Engine bay reservoir marked PSF. COLD marks after a sit. HOT marks after the drive.`,
    why: `The high-pressure hose on this chassis likes to leak. Low fluid is a leak, not a lifestyle.`,
    good: `Near COLD MAX when cold. Red or amber. Dry hose.`,
    bad: `Below MIN, foamy, black/burnt, or a wet hose to the rack.`,
    next: `Pass if in range and dry. Monitor a dusty weep. Shop a wet hose. Nissan PSF only.`,
    tools: `Flashlight, paper towel, Nissan PSF if topping.`,
    specPlain: `Nissan PSF. Do not overfill above the top mark. Do not use ATF unless the cap says so — this truck wants PSF.`,
  }),
  p("fluids.brake", "brake", {
    what: `Brake fluid is what pushes the pads when you press the pedal. It soaks up water over time.`,
    where: `Firewall, driver side, under the hood. Translucent reservoir with MIN/MAX.`,
    why: `A slow drop follows pad wear. A sudden drop is a leak. Dark fluid is old and can boil.`,
    good: `Between MIN and MAX. Light honey color. Cap sealed.`,
    bad: `Below MIN, dark brown/black, or a wet master.`,
    next: `Pass if level and color are fine. Find the leak if it dropped fast. Flush DOT 3 about every 24 months.`,
    tools: `Flashlight, sealed DOT 3 only if topping, moisture tester if you have one.`,
    specPlain: `DOT 3. Flush every 24 months. Never DOT 5 silicone. Never an old open bottle.`,
  }),
  p("fluids.washer", "coolant", {
    what: `Washer fluid is just glass cleaner in a tank so you can see.`,
    where: `Blue or clear tank in the engine bay, usually a blue cap.`,
    why: `Empty washers are a ticket and a safety problem, not an engine problem.`,
    good: `Tank has fluid. Both front and rear washers squirt.`,
    bad: `Empty, or a cracked tank dumping on the ground.`,
    next: `Pass if it squirts. Fill if empty. That is not a shop visit.`,
    tools: `Washer fluid, funnel.`,
    specPlain: `Any washer fluid rated for your climate. Not coolant. Not water in a freeze.`,
  }),
  p("fluids.transferSeep", "under", {
    what: `The transfer case is the box behind the transmission that sends power to both axles on 4WD.`,
    where: `Under the truck, just behind the transmission pan. 4WD only.`,
    why: `A seep here is gear oil, not engine oil. Low fluid lets the chain in that box rattle.`,
    good: `Dry, or a dusty film that does not drip.`,
    bad: `Wet housing, drip, or a puddle of brown gear oil.`,
    next: `Pass if dry. Monitor film. Shop a drip. Skip this on 2WD.`,
    tools: `Flashlight, stands or a lift, paper towel.`,
    specPlain: `No allowed drip. Fill to the plug if you service it — Nissan ATF or the transfer-case spec on the plug tag.`,
  }),
  p("fluids.frontDiffSeep", "under", {
    what: `The front differential is the pumpkin in the front axle that lets the wheels turn different speeds.`,
    where: `Under the front, 4WD only. Look at the cover and the pinion.`,
    why: `Gear oil on the ground is this, not engine oil. A dry diff still needs fluid on a 30k.`,
    good: `Dry cover. No wet pinion seal.`,
    bad: `Wet cover, dripping pinion, or a puddle.`,
    next: `Pass if dry. Shop a wet pinion. Skip on 2WD.`,
    tools: `Flashlight, paper towel, stands.`,
    specPlain: `Hypoid gear oil as tagged on the cover. Seep that wets a finger is a leak.`,
  }),
  p("fluids.rearDiffSeep", "under", {
    what: `The rear differential is the pumpkin in the rear axle.`,
    where: `Under the rear. Cover bolts and the front of the pumpkin (pinion).`,
    why: `Same as the front: gear oil leak vs dusty stain. This one is on 2WD and 4WD.`,
    good: `Dry, or dusty film only.`,
    bad: `Wet cover or wet pinion.`,
    next: `Pass if dry. Monitor film. Shop a drip.`,
    tools: `Flashlight, paper towel, stands.`,
    specPlain: `Hypoid gear oil as tagged. Wet finger = leak.`,
  }),
  p("engine.timingCover", "engine", {
    what: `The timing cover is the front face of the engine. Behind it, a chain keeps the valves in time with the pistons.`,
    where: `Stand in front of the engine. The wide cover low in front. Listen at a cold start — do not rev it.`,
    why: `VK56 chains rattle when oil is slow to get there. A 1–3 second rattle that dies is common. An ongoing rattle with low oil pressure is not.`,
    good: `Quiet, or a short rattle 1–3 seconds then gone, oil pressure in the green.`,
    bad: `Rattle that stays, or rattle plus a low oil-pressure lamp.`,
    next: `Pass if quiet. Monitor a short cold rattle. Do not drive if it keeps rattling and oil pressure is low.`,
    tools: `Ears, a phone timer, oil-pressure gauge in the cluster.`,
    specPlain: `No factory “allowed rattle seconds.” Shop rule: 1–3 sec then gone = watch. Ongoing + low oil = stop.`,
  }),
  p("engine.manifolds", "engine", {
    what: `Exhaust manifolds are the iron pipes bolted to each side of the engine that dump burned gas into the rest of the exhaust.`,
    where: `Each side of the engine, under heat shields. Listen at cold start. Look for soot streaks.`,
    why: `VK56 manifold and heat-shield bolts like to break. A tick that quiets when warm is often a leak at the flange.`,
    good: `Quiet, shields tight, no soot.`,
    bad: `Tick on one side that stays, soot at the flange, loose or missing shield bolts.`,
    next: `Pass if quiet. Monitor a faint warm-up tick. Shop a loud tick or broken bolts.`,
    tools: `Ears, flashlight, a gloved hand only on a cold engine.`,
    specPlain: `No published tick spec. Broken heat-shield bolts are a known 2005 Armada job.`,
  }),
  p("engine.idle", "engine", {
    what: `Idle is how the engine runs in Park, doing nothing. CEL is the check-engine light.`,
    where: `Driver seat, after start. Watch the tach and the dash lamp.`,
    why: `A rough idle or a CEL that stays on means a sensor, vacuum leak, or misfire. Do not ignore it on a 270k VK56.`,
    good: `Smooth idle. CEL proves out then goes off.`,
    bad: `Hunt, shake, or CEL staying on.`,
    next: `Pass if smooth and the lamp is off. Scan it if the CEL stays. Shop a misfire.`,
    tools: `Dash, optional scan tool.`,
    specPlain: `CEL must prove out then off. Idle should sit steady, not hunt.`,
  }),
  p("engine.belt", "engine", {
    what: `The serpentine belt is the long rubber belt that spins the alternator, water pump, and A/C.`,
    where: `Passenger side of the engine. One wide belt on pulleys.`,
    why: `A cracked belt can leave you with no charge and a hot engine. Tensioner play is the squeal you hear.`,
    good: `Quiet, no cracks to the cords, tensioner not flopping.`,
    bad: `Cracks, glaze, fray, or a tensioner that wobbles.`,
    next: `Pass if it looks even and quiet. Monitor light cracks. Shop glaze/fray or a noisy tensioner.`,
    tools: `Flashlight, engine off, a glove to twist the belt slightly.`,
    specPlain: `Replace if cracks reach cords, or if it glazes/squeals. No mile spec that beats a look.`,
  }),
  p("engine.radiator", "radiator", {
    what: `The radiator dumps engine heat. On this Nissan a small ATF cooler is built into an end tank.`,
    where: `Front of the bay, the wide tank behind the grille. Look at plastic end tanks and the two small ATF fittings.`,
    why: `If that cooler fails inside, coolant and transmission fluid mix. That mix can wreck the transmission (SMOD).`,
    good: `Tanks dry, hoses dry, no sweet smell, fittings dry.`,
    bad: `Weeping tanks, wet fittings, crusted seams, or an original radiator at 270k.`,
    next: `Pass if dry and not original-unknown at 270k. Shop wet tanks. Plan a radiator + external cooler if it is still the in-radiator cooler.`,
    tools: `Flashlight, camera, paper towel.`,
    specPlain: `No Nissan “replace by year” line. This shop treats original / 10+ year tanks as due. End-tank cracks are the failure.`,
  }),
  p("engine.atfLines", "radiator", {
    what: `The transmission cooler is built into the radiator. Two small fittings on the end tank carry ATF (automatic transmission fluid) through that tank.`,
    where: `Front of the engine. Passenger-side radiator end tank. Two small lines — not the big upper hose.`,
    why: `If the radiator fails internally, coolant and transmission fluid can mix. On this Nissan that mix can wreck the transmission (SMOD).`,
    good: `ATF is red/clear, not sweet; cooler fittings are dry.`,
    bad: `Milky/pink ATF, wet fittings, unknown original radiator at high miles.`,
    next: `Pink, milky, or sweet-smelling transmission fluid is an emergency — do not keep driving. Pass only if fluid is red and fittings are dry.`,
    tools: `Flashlight, camera, paper towel.`,
    specPlain: `In-radiator cooler still in service at 270k is a plan, not a pass. Wet fittings = shop now even if ATF still looks red.`,
    looksGood: `Dry fittings, red ATF, external cooler already fitted.`,
    secondLook: `Dry today but original radiator — schedule the bypass.`,
    stopShop: `Wet fittings or milky ATF — stop. That is SMOD risk.`,
  }),
  p("engine.airFilter", "engine", {
    what: `The air filter is the paper (or foam) that keeps dirt out of the engine. The cabin filter is the one for the vents inside.`,
    where: `Big black box on the driver side of the bay. Clips or screws on the lid.`,
    why: `A packed filter starves a 5.6 and throws dust into the MAF sensor.`,
    good: `Paper still has color, not mud-packed.`,
    bad: `Caked dirt, wet oil, or missing.`,
    next: `Pass if reasonably clean. Replace if you cannot see light through it. Cabin filter is a 15k item.`,
    tools: `Screwdriver or just the clips, flashlight.`,
    specPlain: `Inspect every 15k. Replace when loaded. No magic mile if you drive dirt roads.`,
  }),
  p("engine.battery", "battery", {
    what: `The battery is the box that starts the truck and feeds the computers.`,
    where: `Driver-side engine bay. Red is +, black is −.`,
    why: `A weak battery on this truck makes lamps and the TCM act possessed. Rest voltage is the number after it sits.`,
    good: `Rest about 12.4–12.8 V. Running about 13.5–14.7 V. Tight clean terminals.`,
    bad: `Rest under 12.2 V, running under 13.2 V, or a failed load test.`,
    next: `Pass if numbers are in range. Monitor 12.3-ish rest. Shop a collapsed rest or a fail load test. Do not drive a no-charge running V.`,
    tools: `Voltmeter, wire brush, flashlight.`,
    specPlain: `Rest under 12.2 V after a sit is a fail. Running should be mid-13s to mid-14s. Load test if you have the tool.`,
  }),
  p("engine.grounds", "battery", {
    what: `Ground straps are the fat black cables that bolt the engine and body to battery negative.`,
    where: `Battery negative to body. Engine block to body. Often a strap at the fender.`,
    why: `A rusty ground on an Armada makes random electrical ghosts — gauges, 4WD, TCM.`,
    good: `Tight, clean metal, not green and crunchy.`,
    bad: `Corroded, loose, or missing.`,
    next: `Pass if tight and clean. Shop a green crust. This is a cheap fix.`,
    tools: `Flashlight, wrench, wire brush.`,
    specPlain: `Metal-to-metal, tight. No factory ohm number you need in the driveway.`,
  }),
  p("engine.pcv", "engine", {
    what: `The PCV hose is the tube that lets crankcase fumes back into the intake so they burn instead of leaking.`,
    where: `Valve cover to intake. Soft hose on top of the engine.`,
    why: `A cracked PCV hose is a vacuum leak — rough idle, whistle, oil breath.`,
    good: `Hose firm, not mush, not wet-oily and split.`,
    bad: `Cracked, collapsed, or soaked and split.`,
    next: `Pass if it looks whole. Replace a split hose. Cheap.`,
    tools: `Eyes, a squeeze with the engine off.`,
    specPlain: `No mile spec that beats a cracked hose. Replace if split.`,
  }),
  p("engine.scan", "cabin", {
    what: `A scan tool talks to the computers. Stored codes are old. Pending are new. ATF temp is the transmission fluid temperature.`,
    where: `OBD plug under the dash, driver side, above your right knee.`,
    why: `This gearbox wants a HOT ATF read near 149°F. The scan confirms you were actually hot. Codes explain a CEL.`,
    good: `No stored/pending that you cannot explain. ATF temp in the HOT window when you read the stick.`,
    bad: `Unexplained CEL codes, or you read ATF cold and called it good.`,
    next: `Pass if clean or known-old. Shop new misfire/TCM codes. 15k item — hidden on oil-change.`,
    tools: `Any ELM/OBD reader that shows ATF temp on Nissan.`,
    specPlain: `HOT check is ATF near 149°F (65°C). Do not treat a 90°F scan as a HOT stick read.`,
  }),
  SHIFT("trans.parkReverse", "Park → Reverse", "a soft clunk, not a bang"),
  SHIFT("trans.reverseDrive", "Reverse → Drive", "a clean take-up, not a slam"),
  SHIFT("trans.up12", "1–2 upshift", "one clean step"),
  SHIFT("trans.up23", "2–3 upshift", "one clean step"),
  SHIFT("trans.up345", "3–4 and 4–5", "clean, no hunt"),
  p("trans.tcc", "trans", {
    what: `TCC is the torque converter clutch — a lock-up that stops the “slip” at cruise so you save fuel and heat.`,
    where: `Driver seat, 45–60 mph, light throttle on a flat road.`,
    why: `A shudder here is a classic RE5R05A complaint. It feels like driving over rumble strips.`,
    good: `Smooth lock, RPM drops a little, no shake.`,
    bad: `Shudder, slip (RPM climbs at the same pedal), or a bang in and out.`,
    next: `Pass if smooth. Monitor a hint of shudder once. Shop a repeatable rumble-strip feel.`,
    tools: `Quiet highway, a passenger to write.`,
    specPlain: `Lock around 45–60 mph light throttle. Shudder is not a spec — it is a fail feel.`,
  }),
  SHIFT("trans.kickdown", "Kickdown 5–4 / 4–3", "a prompt downshift, not a late slam"),
  p("trans.fourwd", "trans", {
    what: `This is the switch that sends power to both axles. 4WD high for slick roads. 4WD low for crawl.`,
    where: `Dash switch. Do this on dirt or a loose surface — not a dry parking lot at speed.`,
    why: `A bind on dry pavement is normal in 4HI if you turn sharp. A “no” when you asked for 4HI is a transfer-case or switch problem.`,
    good: `It engages, light comes on, it disengages.`,
    bad: `No light, no pull, or it stays stuck.`,
    next: `Pass if it works. Shop a no-engage. Skip on 2WD.`,
    tools: `Dirt lot, dash switch.`,
    specPlain: `4HI on loose ground. Do not force 4LO at 30 mph.`,
  }),
  p("trans.atfReject", "atf", {
    what: `This is the stop rule for mixed fluids. ATF (automatic transmission fluid) that looks like a strawberry milkshake is coolant in the gearbox.`,
    where: `Same trans stick. Color and smell on the paper towel.`,
    why: `That mix is SMOD. Keep driving and you can grenade the RE5R05A.`,
    good: `Not this row — you only mark it if the fluid failed.`,
    bad: `Pink, milky, or sweet.`,
    next: `Do not continue the drive. Do not “see if it shifts.” Tow it.`,
    tools: `Paper towel, your nose.`,
    specPlain: `Any pink/milky/sweet ATF is a reject. No “a little pink is OK.”`,
    looksGood: `You did not need this row.`,
    secondLook: `Slight haze — still treat as reject and get a second pair of eyes.`,
    stopShop: `Park it. That is SMOD.`,
  }),
  p("brakes.pads", "pads", {
    what: `Brake pads are the wear blocks that squeeze the shiny rotor to stop you.`,
    where: `Look through each wheel. Inner pad is often thinner — that is the one that lies.`,
    why: `Uneven inner vs outer on this truck often means a sticky caliper or a worn UCA (upper control arm) that lets the wheel lean.`,
    good: `About 6 mm or more remaining, even inner/outer.`,
    bad: `Under 3 mm is thin. 1.0 mm or less is stop. A big inner/outer gap is a caliper or alignment problem.`,
    next: `Pass if even and well above 3 mm. Monitor 3–4 mm. Shop under 3 mm. Do not drive at 1 mm.`,
    tools: `Flashlight, ruler or pad gauge, camera.`,
    specPlain: `Factory min remaining friction is 2 mm on many Nissan pads; this shop treats under 3 mm as due and 1.0 mm as do-not-drive.`,
    looksGood: `Even pads, 5 mm+ meat.`,
    secondLook: `3–4 mm or a little taper.`,
    stopShop: `≤ 1.0 mm — do not drive.`,
  }),
  p("brakes.rotors", "pads", {
    what: `Rotors are the shiny discs the pads grab.`,
    where: `Same wheel opening. Feel the outer edge for a rust lip. Thickness with a micrometer if you have one.`,
    why: `A pulse in the pedal is often a rotor. Too thin and they crack.`,
    good: `Smooth stops, thickness above min, no deep grooves.`,
    bad: `Pulse, cracks, or at/under min thickness.`,
    next: `Pass if smooth and above min. Shop a pulse. Do not drive at min.`,
    tools: `Micrometer or a good caliper, flashlight.`,
    specPlain: `Front min about 26.0 mm, rear about 14.0 mm on this chassis — confirm the stamp on the rotor hat if present.`,
  }),
  p("brakes.hoses", "pads", {
    what: `The caliper is the clamp at each wheel. Hoses are the flexible rubber that feed it fluid.`,
    where: `Behind each wheel. Slide pins are the greasy bolts the caliper slides on.`,
    why: `A wet caliper is a fail. A frozen slide pin eats the inner pad — that is the taper you measured.`,
    good: `Dry caliper, pins move, hoses not cracked to cords.`,
    bad: `Wet, pinned solid, hose cracked or bulging.`,
    next: `Pass if dry and sliding. Shop wet or frozen. Guide has the pin check.`,
    tools: `Flashlight, glove, camera.`,
    specPlain: `No wet caliper. Pins must slide. That is the caliper inspection.`,
  }),
  p("brakes.master", "brake", {
    what: `The master cylinder is the pump your pedal pushes. The booster is the round can behind it that uses engine vacuum to help.`,
    where: `Firewall, driver side, under the hood. Pedal in the cab.`,
    why: `Seepage at the back of the master drips on the booster and then the carpet. A soft pedal is air or a fail master.`,
    good: `Dry, pedal firm after a few pumps.`,
    bad: `Wet at the master, or a pedal that sinks.`,
    next: `Pass if dry and firm. Shop a sink or a wet tail.`,
    tools: `Flashlight, paper towel.`,
    specPlain: `Pedal must hold. Any seepage at the master is a fail.`,
  }),
  p("brakes.pedalHeight", "brake", {
    what: `Pedal height is how far the brake pedal sits off the floor at rest.`,
    where: `Driver footwell. Measure from the floor to the pedal pad.`,
    why: `A low pedal means worn pads, air, or a master that is bypassing. On this truck below spec is a stop.`,
    good: `At or above spec, firm.`,
    bad: `Below 3.5 in at rest, or it sinks while you hold it.`,
    next: `Pass if at spec and firm. Do not drive below spec.`,
    tools: `Tape measure.`,
    specPlain: `Shop rule: under 3.5 in at rest is below spec — do not drive.`,
  }),
  p("brakes.parking", "brake", {
    what: `The parking brake is the pedal or handle that holds the truck on a hill with the transmission in Park as backup.`,
    where: `Left foot pedal on this Armada. Count the clicks. Then try a mild grade.`,
    why: `A parking brake that needs 10 clicks is stretched or seized. One that does not hold is not a parking brake.`,
    good: `About 4–6 clicks, holds a grade.`,
    bad: `Very few clicks (seized) or too many (cable stretch), or it rolls.`,
    next: `Pass if it holds and click count is normal. Shop a roll.`,
    tools: `A mild driveway grade.`,
    specPlain: `Holds the truck. Click count in the middle of the pedal travel — not slammed to the floor.`,
  }),
  p("brakes.absLamps", "cabin", {
    what: `ABS / SLIP / VDC lamps are the anti-lock and stability lights. They must light at key-on, then go out.`,
    where: `Instrument cluster. Key ON. Photograph the cluster.`,
    why: `A lamp that stays on means you may not have anti-lock next time you panic-stop.`,
    good: `Prove-out then off.`,
    bad: `Stays on or comes and goes.`,
    next: `Pass if they go out. Do not drive if ABS stays on and you already have a brake issue. Shop a stay-on lamp.`,
    tools: `Key, camera.`,
    specPlain: `Lamps must prove out then off. Stay-on is a fail and a hard gate with other brake problems.`,
  }),
  p("brakes.tread", "tire", {
    what: `Tread is the rubber grooves that hold the road and the rain.`,
    where: `All four tires plus the spare. Face and the inner shoulder — squat or use a mirror.`,
    why: `Inner-shoulder wipe on this truck is often alignment or a tired UCA, not “I need new tires only.”`,
    good: `Even, well above 4/32, inner shoulder not bald.`,
    bad: `At 2/32, inner bald, or one tire much lower than its pair.`,
    next: `Pass if even and healthy. Monitor inner wear. Shop 2/32 or a bald inner.`,
    tools: `Tread gauge, flashlight, camera.`,
    specPlain: `Legal often 2/32. This shop treats 4/32 as “plan it” and a bald inner as alignment, not just rubber.`,
  }),
  p("brakes.tireAge", "tire", {
    what: `DOT week/year is the four-digit date on the sidewall. 2318 means week 23 of 2018.`,
    where: `Sidewall of each tire including the spare. You may need to roll the tire or crawl.`,
    why: `Old rubber cracks even with tread. Six to seven years is old for a daily.`,
    good: `Date in the last 5–6 years.`,
    bad: `7+ years, or a spare from the Bush administration.`,
    next: `Pass if dates are sane. Monitor 6–7 years. Shop older, even with tread.`,
    tools: `Flashlight, a wipe for the sidewall.`,
    specPlain: `No Nissan “expire at 6 years” line. Industry practice: replace around 6–10 years. This shop flags 7+.`,
  }),
  p("brakes.wear", "tire", {
    what: `Wear pattern is the shape of the remaining rubber — even, inner, outer, cup, or center.`,
    where: `Same as tread. Compare left vs right.`,
    why: `Inner wear + a pull is alignment or UCA play. Catch it before the rotor is scrap.`,
    good: `Even across the face.`,
    bad: `Inner wipe, feathering, cupping.`,
    next: `Pass if even. Monitor a hint of inner. Shop a wipe plus a pull.`,
    tools: `Eyes, camera, the alignment-feel row.`,
    specPlain: `Uneven wear is a diagnosis, not a tire brand problem until the alignment is proven.`,
  }),
  p("brakes.pressures", "tire", {
    what: `Air in the tires. Cold numbers, before you drive.`,
    where: `Door sticker is the spec. All four plus spare.`,
    why: `Low inner heat cooks a tire. High center wear. The spare is often at 20 psi from 2005.`,
    good: `At the door-sticker psi, spare usable.`,
    bad: `Grossly low, or spare flat.`,
    next: `Pass if set. Fill the spare. That is not a shop visit unless it will not hold.`,
    tools: `Gauge, compressor.`,
    specPlain: `Use the door sticker, not the sidewall max. Typical Armada is in the mid-30s psi — read the sticker.`,
  }),
  p("brakes.lugTorque", "tire", {
    what: `Lug nuts hold the wheels on. Torque is how tight, in foot-pounds.`,
    where: `Each wheel. Recheck after a recent tire or brake job.`,
    why: `Too loose = wheel walks. Too tight = broken studs. 98 ft-lb is this truck.`,
    good: `Rechecked to 98 ft-lb in a star pattern.`,
    bad: `Never rechecked after a wheel-off, or a spinning stud.`,
    next: `Pass if you rechecked. Do not skip after pads. 15k item.`,
    tools: `Torque wrench, 21 mm socket typical.`,
    specPlain: `98 ft-lb. Star pattern. Recheck after 50–100 miles if you just installed wheels.`,
  }),
  p("brakes.bearings", "tire", {
    what: `Wheel bearings let the wheel spin. A bad one growls or has play.`,
    where: `Grab 12 and 6 on each wheel (truck in air or with a helper). Road noise that follows a corner.`,
    why: `A growl that changes in a turn is a bearing, not a tire. Play at the rim is not OK.`,
    good: `No growl, no play.`,
    bad: `Growl in a turn, or clunk play.`,
    next: `Pass if quiet and tight. Shop a growl. Do not wait for it to roar.`,
    tools: `Quiet road, hands on the tire at 12 and 6.`,
    specPlain: `No perceptible play. Growl that follows a side is that side’s bearing.`,
  }),
  p("brakes.alignment", "steering", {
    what: `Alignment is whether the truck goes straight with your hands light on the wheel.`,
    where: `A straight, flat road. Note pull, wander, or a wheel that is not centered.`,
    why: `A pull plus inner pad taper is a UCA or inner-tie-rod story on this chassis.`,
    good: `Tracks straight, wheel centered.`,
    bad: `Pull L/R, wander, or a crooked wheel.`,
    next: `Pass if it tracks. Monitor a hint. Shop a pull, especially with inner tire wear.`,
    tools: `Straight road, hands light.`,
    specPlain: `No factory “degrees of pull” in the driveway. Pull that you can feel is a shop alignment after you fix worn parts.`,
  }),
  p("steering.steeringPlay", "steering", {
    what: `Steering play is dead motion in the wheel before the tires move.`,
    where: `Engine idling, wheels on the ground. Watch a tire while you wiggle the wheel.`,
    why: `Play here is the box, the column, or the joints you check next.`,
    good: `Small, tight motion.`,
    bad: `You can rock the wheel a lot before the tire moves.`,
    next: `Pass if tight. Shop obvious play. 15k item.`,
    tools: `A helper to watch the tire, or a mirror.`,
    specPlain: `Minimal free play. If the tire does not move when the wheel does, keep looking at joints.`,
  }),
  p("steering.tieRods", "steering", {
    what: `Tie rods are the links from the steering rack to the wheels. Inner and outer.`,
    where: `Behind the front wheels, along the rack. Jacked, wheels hanging or on stands.`,
    why: `A loose tie rod is clunk + inner tire wear + a death wobble risk.`,
    good: `No clunk, boots intact, joints tight.`,
    bad: `Clunk, torn boot, or a joint that clicks.`,
    next: `Pass if tight. Shop play. 15k.`,
    tools: `Hands, flashlight, stands.`,
    specPlain: `No perceptible play at the joint. Torn boot means the joint is next.`,
  }),
  p("steering.ballJoints", "steering", {
    what: `Ball joints are the pivots that let the wheel steer and move up and down. UCA is the upper control arm — the top A-arm that holds those joints.`,
    where: `Front, top and bottom of the knuckle. Wheel off or turned out helps.`,
    why: `Tired UCAs on this truck eat inner pads and ruin alignments. That is why pad taper and a pull travel together.`,
    good: `No play, boots intact.`,
    bad: `Clunk, torn boot, or visible play at the UCA.`,
    next: `Pass if tight. Shop play. Photograph it. 15k / baseline.`,
    tools: `Pry bar gently, flashlight, camera, stands.`,
    specPlain: `No perceptible play. Replace as a pair if one UCA is gone.`,
    looksGood: `Tight, dry boots.`,
    secondLook: `Dry but dusty boot — watch.`,
    stopShop: `Play you can see — shop before the next highway trip.`,
  }),
  p("steering.sway", "steering", {
    what: `The sway bar is the bar that keeps the body from leaning in a turn. Bushings and end links connect it.`,
    where: `Front (and rear) bar, links up to the control arms.`,
    why: `A clunk over driveways is often these, not the transmission.`,
    good: `Quiet, bushings not torn out.`,
    bad: `Clunk, missing link, torn bushing.`,
    next: `Pass if quiet. Shop a clunk. Cheap compared to UCAs.`,
    tools: `Hands, flashlight.`,
    specPlain: `No torn bushings, no broken links.`,
  }),
  p("steering.springs", "steering", {
    what: `Springs hold the truck up. Perches and shackles are the mounts. Body mounts sit between frame and body.`,
    where: `Front coils / rear springs, shackles at the rear, body mounts along the frame.`,
    why: `A collapsed perch or a rotten body mount changes alignment and pad wear.`,
    good: `Even ride height, no cracked perches, mounts not mush.`,
    bad: `Sag, cracked perch, rotting mount.`,
    next: `Pass if even and solid. Shop sag or rot.`,
    tools: `Eyes, tape for ride height L vs R.`,
    specPlain: `Even side to side. Cracked perch is a fail.`,
  }),
  p("steering.shocks", "steering", {
    what: `Shocks control bounce. Struts are the front combo units. A wet shock is a leak.`,
    where: `Each corner, on the body of the shock.`,
    why: `A wet shock plus inner tire cupping is a replace, not an alignment first.`,
    good: `Dry, bounce settles in one or two motions.`,
    bad: `Wet streak, bounce that will not die.`,
    next: `Pass if dry. Shop wet. Replace as a pair.`,
    tools: `Paper towel, bounce test.`,
    specPlain: `Wet body = leak. No factory cc of oil allowed.`,
  }),
  p("steering.rack", "steering", {
    what: `The steering rack is the bar that turns both front wheels. Boots cover the inner joints. The high-pressure hose feeds it PSF.`,
    where: `Front, low, behind the engine. Boots at each end. Hose from the pump.`,
    why: `A torn boot dumps grease and then play. A wet hose is a tow-home leak.`,
    good: `Dry hose, intact boots.`,
    bad: `Torn boot, wet PSF hose.`,
    next: `Pass if dry and intact. Shop wet. Do not keep topping.`,
    tools: `Flashlight, paper towel.`,
    specPlain: `Boots whole. Hose dry. Nissan PSF only.`,
  }),
  p("steering.shafts", "steering", {
    what: `Drive shafts take power to the axles. U-joints are the crosses. The slip yoke slides at the transfer case.`,
    where: `Under the truck, front and rear shafts. 4WD has both.`,
    why: `A vibration 45–70 that you did not have last year is often a U-joint, not “tires.”`,
    good: `No clunk, no rusted-solid U-joint, boot on a CV intact.`,
    bad: `Clunk on take-off, seized U-joint, torn CV boot.`,
    next: `Pass if smooth. Shop a clunk. 4WD skip front shaft on 2WD.`,
    tools: `Hands on the joint (truck in Park, stands), flashlight.`,
    specPlain: `U-joints must flex without notch. Torn CV boot is a shop.`,
  }),
  p("steering.seals", "steering", {
    what: `These are the rubber seals where axles leave the diffs and where CVs meet the joint.`,
    where: `Front and rear pumpkin edges, CV inners.`,
    why: `A wet seal is gear oil or grease leaving. Low fluid follows.`,
    good: `Dry.`,
    bad: `Wet ring, flung oil.`,
    next: `Pass if dry. Shop wet.`,
    tools: `Flashlight, paper towel.`,
    specPlain: `Wet = leak. No allowed seepage once it flings.`,
  }),
  p("steering.mounts", "steering", {
    what: `Engine and transmission mounts are the rubber blocks that hold the powertrain to the frame.`,
    where: `Sides of the engine, rear of the transmission. Have a helper blip Drive and Reverse with the brake on.`,
    why: `A torn mount lets the engine jump and can look like a slam shift.`,
    good: `Little rock, rubber not separated.`,
    bad: `Big clunk, rubber torn through.`,
    next: `Pass if tight. Shop a torn mount.`,
    tools: `Helper, brake on, eyes on the mount.`,
    specPlain: `No separated rubber. Excess rock in gear is a fail.`,
  }),
  p("underbody.oilPan", "under", {
    what: `The oil pan is the steel bathtub under the engine. The drain plug is the bolt you pull on an oil change.`,
    where: `Dead center front under the engine.`,
    why: `A leaking pan rail or a reused crush washer drips the oil you just paid for.`,
    good: `Dry rail, new washer, no drip.`,
    bad: `Wet rail, dripping plug.`,
    next: `Pass if dry. Shop a drip. New washer every drain.`,
    tools: `Flashlight, paper towel.`,
    specPlain: `New crush washer every oil change. Confirm plug torque in the FSM — do not guess.`,
  }),
  p("underbody.transPan", "under", {
    what: `The transmission pan is the wide pan under the gearbox. Cooler fittings are those two small lines at the radiator — also check them from below.`,
    where: `Mid truck, under the transmission. Fittings also at the radiator tank.`,
    why: `Wet fittings from below are the same SMOD story. Pan seepage is fluid you will be adding.`,
    good: `Dry pan, dry fittings.`,
    bad: `Wet pan or wet cooler lines.`,
    next: `Pass if dry. Shop wet. Photograph fittings.`,
    tools: `Flashlight, camera, paper towel.`,
    specPlain: `Wet cooler fittings = SMOD risk even if ATF still looks red.`,
  }),
  p("underbody.fuel", "under", {
    what: `Fuel tank, straps, lines, and the EVAP (vapor) bits. EVAP is the system that keeps gas vapor in the can, not in the air.`,
    where: `Under the rear. Tank held by straps. Lines along the frame.`,
    why: `A fuel smell or a wet line is a fire problem, not a “next oil change” problem.`,
    good: `Dry, straps intact, no raw-fuel smell.`,
    bad: `Wet line, rusted-through strap, strong fuel smell.`,
    next: `Pass if dry. Do not drive a wet fuel line.`,
    tools: `Flashlight, nose, camera.`,
    specPlain: `Any wet fuel is a stop. Straps must be whole.`,
  }),
  p("underbody.exhaust", "under", {
    what: `Exhaust is the pipe from the manifolds back: cats, muffler, hangers, heat shields.`,
    where: `Full length underside. Heat shields over cats and near the cab.`,
    why: `Broken hangers drag. Shield bolts on this truck rattle and then fall on the highway.`,
    good: `Hung, no blow, shields present.`,
    bad: `Blow at a flange, hanging shield, broken hanger.`,
    next: `Pass if quiet and hung. Shop a blow or a dragging shield.`,
    tools: `Ears (cold), flashlight, a glove on a cold pipe only.`,
    specPlain: `No leaks, hangers intact, shields present. VK56 heat-shield bolts are a known miss.`,
  }),
  p("underbody.frame", "under", {
    what: `The frame is the steel ladder the body sits on. Spare-tire carrier hangs under the rear.`,
    where: `Rails from bumper to bumper. Spare winch under the rear.`,
    why: `Rust at running-board mounts and the spare carrier is how these trucks get dangerous, not just ugly.`,
    good: `Surface rust only, carrier works, mounts solid.`,
    bad: `Scale you can poke through, frozen spare winch, rotten board mounts.`,
    next: `Pass if solid. Shop rot you can poke. Photograph it.`,
    tools: `Flashlight, a screwdriver to probe (gently), camera.`,
    specPlain: `No perforation in load paths. Spare must come down.`,
  }),
  p("underbody.lines", "under", {
    what: `Steel brake and fuel lines run along the frame.`,
    where: `Inside the frame rails, front to back.`,
    why: `Rusty brake line is a blowout later. Fuel line rust is a fire.`,
    good: `Surface film, still round, no flakes.`,
    bad: `Flaking rust, wet, crimped.`,
    next: `Pass if solid. Shop flaking brake lines before a long trip.`,
    tools: `Flashlight, camera.`,
    specPlain: `Brake lines must be round and dry. Flake-off rust is a replace.`,
  }),
  p("cabin.airbag", "cabin", {
    what: `The airbag lamp is the light that says the bags are ready. It must come on at key-on, then go out.`,
    where: `Cluster. Key ON.`,
    why: `A bag lamp that stays on means the bag may not fire — or may fire for no reason. That is a stop with other faults.`,
    good: `Prove-out then off.`,
    bad: `Stays on or blinks.`,
    next: `Pass if it goes out. Shop a stay-on. Do not drive if it stays on and you already have brake/electrical chaos.`,
    tools: `Key, camera.`,
    specPlain: `Must prove out then off. Stay-on is a hard gate.`,
  }),
  p("cabin.seatbelts", "cabin", {
    what: `Seatbelts latch and pull back in. All rows, including the third.`,
    where: `Every seating position.`,
    why: `A belt that will not latch is not a “later” item.`,
    good: `Latches, retracts, no cuts.`,
    bad: `Will not click, stuck, or sliced webbing.`,
    next: `Pass if all work. Shop a dead latch. Do not drive kids on a dead belt.`,
    tools: `Your hands.`,
    specPlain: `Every position latches and retracts. Cuts in webbing are a replace.`,
  }),
  p("cabin.latches", "cabin", {
    what: `Doors, rear hatch, and the flip-up rear glass must latch.`,
    where: `All four doors, hatch, glass.`,
    why: `A hatch that pops on the highway is a wreck, not an annoyance.`,
    good: `All click shut, no dash “door ajar” lie.`,
    bad: `Will not latch, or glass that pops.`,
    next: `Pass if they click. Shop a hatch that will not die.`,
    tools: `Your hands. Open and shut each one.`,
    specPlain: `Must stay shut. Ajar lamp with a shut door is still a fail of the switch or latch.`,
  }),
  p("cabin.horn", "cabin", {
    what: `The horn is the button in the wheel that makes noise so people look up.`,
    where: `Steering-wheel pad.`,
    why: `A dead horn is a safety fail and a ticket in some places.`,
    good: `Loud, both tones if it has two.`,
    bad: `Dead or a weak chirp.`,
    next: `Pass if it honks. Shop a dead one.`,
    tools: `Your palm.`,
    specPlain: `Must sound. Clock-spring issues can kill the horn and the bag lamp together.`,
  }),
  p("cabin.lights", "cabin", {
    what: `Lights: headlights, high beams, fogs, tails, brake, reverse, plate, hazards.`,
    where: `Walk around. A helper on the brake and the shifter in Reverse (brake on).`,
    why: `A dark brake light is how someone finds your bumper.`,
    good: `All work, lenses not opaque white.`,
    bad: `Out bulb, water in a lamp, no reverse lights.`,
    next: `Pass if the walk-around is complete. Replace bulbs. Shop a wet housing.`,
    tools: `Helper, dark-ish spot.`,
    specPlain: `Every required lamp works. Hazards too.`,
  }),
  p("cabin.wipers", "cabin", {
    what: `Wipers and washers, front and rear.`,
    where: `In the seat. Rear wiper on the hatch.`,
    why: `You cannot inspect what you cannot see in a Ventura County marine layer.`,
    good: `Clears the glass, washers squirt front and rear.`,
    bad: `Streaks to the bone, rear dead, no squirt.`,
    next: `Pass if they clear. Blades are DIY. Shop a dead motor.`,
    tools: `Washer fluid, the stalk.`,
    specPlain: `Front and rear wipe. Washers wet the glass.`,
  }),
  p("cabin.hvac", "cabin", {
    what: `Defroster and the blower are how you see and breathe. HVAC is heating, vent, air conditioning.`,
    where: `Dash. Defrost at the windshield. Blower speed 1–4.`,
    why: `No defrost in a rain is a safety fail.`,
    good: `Air at the windshield, blower on all speeds, A/C blows cold if equipped.`,
    bad: `Dead blower, no defrost, A/C warm in summer.`,
    next: `Pass if defrost and blower work. Shop a dead blower. A/C can wait if it is not safety.`,
    tools: `The knobs, a minute of run time.`,
    specPlain: `Defrost must hit the glass. Blower must run.`,
  }),
  p("cabin.glass", "cabin", {
    what: `Mirrors and glass. Cracks in the view are a problem.`,
    where: `Windshield, all side glass, both mirrors, rear glass.`,
    why: `A crack in the driver’s view is a ticket and a blow risk.`,
    good: `No crack in the wiper sweep. Mirrors intact.`,
    bad: `Star in the sweep, missing mirror glass.`,
    next: `Pass if clear. Shop a sweep crack.`,
    tools: `Eyes, camera.`,
    specPlain: `No damage in the driver’s essential view. Mirror glass present.`,
  }),
  p("cabin.jack", "cabin", {
    what: `Jack, lug wrench, and the spare — so a flat is a delay, not a tow.`,
    where: `Spare under the rear. Jack often in a side bin or under a seat. Try the spare winch.`,
    why: `A frozen spare carrier is a 2005 Armada classic. You find out on the shoulder.`,
    good: `Spare holds air, wrench fits, jack present, carrier works.`,
    bad: `No jack, frozen winch, spare at 10 psi.`,
    next: `Pass if the kit works. Fix a frozen winch before a trip.`,
    tools: `Gauge, the factory wrench, a minute with the winch.`,
    specPlain: `Spare present and usable. Carrier must lower. Lug wrench matches the lugs.`,
  }),
  p("cabin.recalls", "cabin", {
    what: `A recall is a free factory fix Nissan (or NHTSA) still owes this VIN.`,
    where: `You look it up from the VIN plate — dash, driver side, visible through the glass.`,
    why: `Airbag and sensor campaigns on this era are real. A dated check is what makes the paper form defensible later.`,
    good: `VIN checked today, stamp on the form, open campaigns listed or “none.”`,
    bad: `Skipped, or a VIN that is not 17 characters.`,
    next: `Run the check. Pass if none open. Shop/dealer if an open campaign is a safety one.`,
    tools: `VIN, phone, the in-app Nissan campaign button.`,
    specPlain: `Dated “checked Nissan campaign list on [date]” with this VIN. Not a checkbox from memory.`,
  }),
  p("road.coldStart", "engine", {
    what: `A cold start is the first start of the visit, before the engine is warm.`,
    where: `Driveway. Listen. Do not rev.`,
    why: `Timing-cover rattle and manifold tick show up here, then hide when hot.`,
    good: `Fires, idle settles, rattle gone in 1–3 sec or never there.`,
    bad: `Ongoing rattle, no-start, or a CEL that stays.`,
    next: `Pass if it settles. Pair this with the timing-cover and manifold rows.`,
    tools: `Ears, a timer.`,
    specPlain: `Same as the timing-cover row. Do not rev a cold VK56 to “clear it.”`,
  }),
  p("road.overheat", "coolant", {
    what: `The temp gauge is the needle that says the engine is not boiling.`,
    where: `Cluster, during a 15-minute mixed drive.`,
    why: `A climb past the middle on this truck is a radiator, cap, or fan story — and it can become SMOD if the tanks are original.`,
    good: `Needle stays in the normal middle.`,
    bad: `Climb, hot warning, or steam.`,
    next: `Pass if stable. Stop if it climbs. Do not keep driving hot.`,
    tools: `A mixed loop, eyes on the gauge.`,
    specPlain: `Gauge stable in the normal range. Any climb after 15 min mixed driving is a fail.`,
  }),
  p("road.brakes", "pads", {
    what: `A real stop from 30 and from 60, not a parking-lot poke.`,
    where: `Quiet road. No one behind you.`,
    why: `Pull and pulse show up at speed. That is pads, rotors, or a caliper.`,
    good: `Straight, no pulse, no pull.`,
    bad: `Pull, pulse, grind, or a long pedal.`,
    next: `Pass if straight and quiet. Shop a pulse/pull. Stop if it grinds metal.`,
    tools: `Safe road.`,
    specPlain: `No pull, no pulse from 30 and from 60.`,
  }),
  p("road.vibration", "tire", {
    what: `A shake in the wheel or seat between 45 and 70 that you did not have last year.`,
    where: `Highway, light hands.`,
    why: `Tires, a U-joint, or a bent wheel. New vibration is a find-it, not “the freeway is rough.”`,
    good: `Smooth.`,
    bad: `New shake in that band.`,
    next: `Pass if smooth. Shop a new vibration. 15k item.`,
    tools: `A highway loop.`,
    specPlain: `No new vibration 45–70 mph.`,
  }),
  p("road.shifts", "trans", {
    what: `This is a check that the road still matches the shift table you already filled.`,
    where: `The same loop.`,
    why: `A flare that only happens hot will show here, not in the driveway.`,
    good: `Matches the table. No new bang.`,
    bad: `New flare or bang that the table missed.`,
    next: `Pass if it matches. Shop a new harsh shift. Skip the loop if ATF is milky.`,
    tools: `The filled shift table.`,
    specPlain: `Shift quality matches Section 3. No new faults.`,
  }),
  p("road.lamps", "cabin", {
    what: `Warning lamps that were off should stay off after the drive.`,
    where: `Cluster, after the loop.`,
    why: `A lamp that appears hot is a real fault, not a prove-out.`,
    good: `No new lamp.`,
    bad: `CEL, ABS, bag, or SLIP that was not there.`,
    next: `Pass if the cluster is as you left it. Shop a new stay-on lamp.`,
    tools: `Eyes, camera.`,
    specPlain: `No new warning lamps.`,
  }),
  p("baseline.sparkPlugs", "engine", {
    what: `Spark plugs are the igniters in each cylinder. This engine uses long-life iridium plugs.`,
    where: `Under coils on top of each bank. 8 of them.`,
    why: `The interval is 105k. At 270k you are on cycle 2 or 3 — they are due unless you have a dated receipt.`,
    good: `Dated service within 105k, or you just did them.`,
    bad: `Unknown, or way past 105k since last.`,
    next: `Pass with a receipt. Fail unknown at 270k. This is a baseline grade, not a note.`,
    tools: `Records, or a shop to pull one plug.`,
    specPlain: `Iridium interval 105,000 miles. Cycle 2 or 3 at 270k.`,
  }),
  p("baseline.coolantService", "coolant", {
    what: `A coolant service is drain, flush, new cap, and a look at the thermostat and the water-pump weep hole.`,
    where: `Radiator, cap, thermostat housing, weep at the pump (small hole on the pump body).`,
    why: `Unknown coolant at 270k is rust and a popped tank waiting. A wet weep is a pump about to go.`,
    good: `Dated service, dry weep, cap in date.`,
    bad: `Unknown, wet weep, rusty sludge.`,
    next: `Pass with a dated service and a dry weep. Fail unknown. Baseline grade.`,
    tools: `Records, flashlight on the weep.`,
    specPlain: `About 60k / 5 years if unknown. Weep hole must be dry.`,
  }),
  p("baseline.brakeFluid", "brake", {
    what: `Brake fluid service is a DOT 3 flush and a moisture check.`,
    where: `Same master cylinder. Moisture tester if you have one.`,
    why: `Old DOT 3 eats internals and boils on a long grade.`,
    good: `Flushed inside 24 months, light color, dry moisture.`,
    bad: `Black fluid, high moisture, unknown at 270k.`,
    next: `Pass with a dated flush. Fail unknown or wet. Baseline grade.`,
    tools: `Moisture tester, sealed DOT 3.`,
    specPlain: `DOT 3. Flush every 24 months. High moisture is a fail.`,
  }),
  p("baseline.diffFluid", "under", {
    what: `Diff and transfer-case fluid is the oil in the pumpkins and the 4WD box — not just a look for seep.`,
    where: `Fill plugs on front diff (4WD), rear diff, transfer case.`,
    why: `At 270k “it isn’t dripping” is not a fluid change. Metal in the oil is a warning.`,
    good: `Dated service, clean-ish oil on the plug.`,
    bad: `Unknown, glitter, burnt.`,
    next: `Pass with a dated service. Fail unknown. Baseline grade.`,
    tools: `Records, 10 mm / square plug as fitted.`,
    specPlain: `Service at 30k cadence. Baseline at 270k wants a dated change, not a dry housing.`,
  }),
  p("baseline.seepage", "leak", {
    what: `Seepage grade is how wet the gaskets are: dry, film, wet, or drip.`,
    where: `Valve covers, timing cover, oil pan.`,
    why: `A drip is a leak. A film is a watch. Calling a drip “high miles” is how the stick goes empty.`,
    good: `Dry or light film.`,
    bad: `Wet or drip.`,
    next: `Pass dry/film. Fail wet/drip. Photograph. Baseline grade.`,
    tools: `Flashlight, paper towel, camera.`,
    specPlain: `Dry / film / wet / drip. Wet and drip are Fail.`,
  }),
  p("baseline.manifoldBolts", "engine", {
    what: `Exhaust manifold and heat-shield bolts on this VK56 like to snap and rattle.`,
    where: `Each bank, shields over the manifolds.`,
    why: `A ticking heat shield is annoying. A broken manifold bolt is a leak and a repair.`,
    good: `Bolts present, shields quiet.`,
    bad: `Missing bolts, rattle, soot.`,
    next: `Pass if present and quiet. Fail missing/broken. Baseline grade.`,
    tools: `Flashlight, ears, cold engine.`,
    specPlain: `All shield and manifold fasteners present. VK56 classic.`,
  }),
  p("baseline.ucaJoints", "steering", {
    what: `Upper control arms and ball joints — same parts as the steering row, graded Pass/Fail at 270k.`,
    where: `Front, top A-arms.`,
    why: `Play here is inner pad taper and a pull. At 270k this is due or proven tight.`,
    good: `Tight, boots intact.`,
    bad: `Play, torn boot.`,
    next: `Pass if tight. Fail play. Baseline grade.`,
    tools: `Pry bar, flashlight, camera.`,
    specPlain: `No play. Replace as a pair. Ties to alignment and inner pad taper.`,
  }),
  p("baseline.airShocks", "steering", {
    what: `Some Armadas have rear load-leveling / air shocks instead of plain shocks.`,
    where: `Rear shocks. Air lines and a compressor mean equipped.`,
    why: `A sagging rear with a compressor that never sleeps is a leak, not “it is old.”`,
    good: `Not equipped (Pass), or equipped, level, dry, compressor quiet.`,
    bad: `Sag, wet air shock, compressor short-cycling.`,
    next: `Pass if not equipped or if equipped and healthy. Fail sag/leak. Baseline grade.`,
    tools: `Eyes, bounce, listen after a door slam.`,
    specPlain: `Equipped Y/N. If Y: level, dry, compressor not constant.`,
  }),
  p("result.smodPlan", "radiator", {
    what: `The transmission cooler is built into the radiator. Prevention means an external cooler and a new radiator before they mix.`,
    where: `Radiator end-tank fittings, plus a date on the radiator if it was replaced.`,
    why: `At 270k, “not milky today” is not a maintenance plan. Detection is SMOD. This row is prevention.`,
    good: `External cooler in, radiator dated, fittings photo on file, ATF still red.`,
    bad: `Original or unknown radiator, in-radiator cooler still in service, no fittings photo.`,
    next: `Do not Pass because it is not milky today. Schedule the cooler + radiator. If ATF is already milky, stop — prevention is too late.`,
    tools: `Camera, the radiator date, a shop that will cap the old ports.`,
    specPlain: `This shop’s 30k / 270k action: external stacked-plate cooler, cap the in-radiator ports, replace an original/unknown radiator.`,
    looksGood: `Bypass done, radiator dated, photo on file.`,
    secondLook: `Still red ATF, original radiator — schedule it.`,
    stopShop: `Already milky — do not bypass-and-drive.`,
  }),
  p("result.overall", "cabin", {
    what: `This is the one-line verdict for the whole visit.`,
    where: `End of the form. Score and flags already sat at the top.`,
    why: `Pass is blocked if a hard gate is open: SMOD, pad at 1 mm, rotor at min, dead rest voltage, ABS/airbag lamp staying on, low pedal, ongoing timing rattle plus low oil.`,
    good: `No hard gates. Pass or Pass with notes for watch items.`,
    bad: `Any Repair ASAP / do-not-drive gate.`,
    next: `Do not circle Pass to be nice. Schedule repairs or Do not drive when the gates say so.`,
    tools: `The score header, the fail-item list, a pen.`,
    specPlain: `Hard gates auto-block Pass. Score starts at 100, minus 15 / 6 / 2 for ASAP / attention / monitor.`,
  }),
  p("engine.overview", "engine", {
    what: `One wide photo of the whole bay so a shop or a spouse can see tanks, belt, battery, and leaks in context.`,
    where: `Stand at the front bumper, hood open, before you start moving things.`,
    why: `A close-up of a fitting without this shot is hard to trust later.`,
    good: `Level, lit, tanks and battery in frame.`,
    bad: `Dark, cropped, or taken after you already cleaned the evidence.`,
    next: `Required photo. Take it first.`,
    tools: `Phone camera.`,
    specPlain: `Required on this visit. One wide shot.`,
  }),
  p("cabin.dash", "cabin", {
    what: `A photo of the dash with the key on, so the prove-out (or a lamp that stayed) is on the paper.`,
    where: `Driver seat, cluster in frame.`,
    why: `“I think the ABS went out” is not a photo. This is.`,
    good: `Cluster readable, key on.`,
    bad: `Glare, engine already running and you missed prove-out.`,
    next: `Required photo. Take it at key-on.`,
    tools: `Phone camera.`,
    specPlain: `Required. Key on.`,
  }),
];

const BY_ID = new Map(PLAIN.map((x) => [x.id, x]));

export function plainFor(id: string): PlainExplain | undefined {
  return BY_ID.get(id);
}

export function cardBody(p: PlainExplain): { whyMatters: string; good: string; bad: string } {
  return { whyMatters: p.why, good: p.good, bad: p.bad };
}
